; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=thumbv8-linux-gnueabihf -mattr=neon -debug 2>&1 | FileCheck %s
; REQUIRES: asserts

declare float @llvm.pow.f32(float, float)
declare <4 x float> @llvm.pow.v4f32(<4 x float>, <4 x float>)
declare double @llvm.pow.f64(double, double)
declare <2 x double> @llvm.pow.v2f64(<2 x double>, <2 x double>)

define float @pow_f32_three_fourth_fmf(float %x) nounwind {
; CHECK-LABEL: pow_f32_three_fourth_fmf:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vsqrt.f32 s0, s0
; CHECK-NEXT:    vsqrt.f32 s2, s0
; CHECK-NEXT:    vmul.f32 s0, s0, s2
; CHECK-NEXT:    bx lr
  %r = call nsz ninf afn float @llvm.pow.f32(float %x, float 7.5e-01)
  ret float %r
}

define double @pow_f64_three_fourth_fmf(double %x) nounwind {
; CHECK-LABEL: pow_f64_three_fourth_fmf:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vsqrt.f64 d16, d0
; CHECK-NEXT:    vsqrt.f64 d17, d16
; CHECK-NEXT:    vmul.f64 d0, d16, d17
; CHECK-NEXT:    bx lr
  %r = call nsz ninf afn double @llvm.pow.f64(double %x, double 7.5e-01)
  ret double %r
}

define <4 x float> @pow_v4f32_three_fourth_fmf(<4 x float> %x) nounwind {
; CHECK-LABEL: pow_v4f32_three_fourth_fmf:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vsqrt.f32 s4, s3
; CHECK-NEXT:    vsqrt.f32 s6, s2
; CHECK-NEXT:    vsqrt.f32 s8, s1
; CHECK-NEXT:    vsqrt.f32 s10, s0
; CHECK-NEXT:    vsqrt.f32 s0, s4
; CHECK-NEXT:    vsqrt.f32 s12, s6
; CHECK-NEXT:    vsqrt.f32 s14, s8
; CHECK-NEXT:    vsqrt.f32 s5, s10
; CHECK-NEXT:    vmul.f32 s3, s4, s0
; CHECK-NEXT:    vmul.f32 s2, s6, s12
; CHECK-NEXT:    vmul.f32 s1, s8, s14
; CHECK-NEXT:    vmul.f32 s0, s10, s5
; CHECK-NEXT:    bx lr
  %r = call fast <4 x float> @llvm.pow.v4f32(<4 x float> %x, <4 x float> <float 7.5e-1, float 7.5e-1, float 7.5e-01, float 7.5e-01>)
  ret <4 x float> %r
}

define <2 x double> @pow_v2f64_three_fourth_fmf(<2 x double> %x) nounwind {
; CHECK-LABEL: pow_v2f64_three_fourth_fmf:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vsqrt.f64 d16, d1
; CHECK-NEXT:    vsqrt.f64 d17, d0
; CHECK-NEXT:    vsqrt.f64 d18, d16
; CHECK-NEXT:    vsqrt.f64 d19, d17
; CHECK-NEXT:    vmul.f64 d1, d16, d18
; CHECK-NEXT:    vmul.f64 d0, d17, d19
; CHECK-NEXT:    bx lr
  %r = call fast <2 x double> @llvm.pow.v2f64(<2 x double> %x, <2 x double> <double 7.5e-1, double 7.5e-1>)
  ret <2 x double> %r
}
