; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mcpu=pwr8 -ppc-asm-full-reg-names -ppc-vsr-nums-as-vr \
; RUN:   -mtriple=powerpc64le-unknown-unknown < %s | FileCheck %s

define <32 x i16> @backsmith_pure_7(<8 x i8> %conv) {
; CHECK-LABEL: backsmith_pure_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vspltisw v3, 1
; CHECK-NEXT:    addis r7, r2, .LCPI0_0@toc@ha
; CHECK-NEXT:    li r5, 1
; CHECK-NEXT:    li r3, 0
; CHECK-NEXT:    xxlxor v7, v7, v7
; CHECK-NEXT:    addi r7, r7, .LCPI0_0@toc@l
; CHECK-NEXT:    mtvsrd v5, r3
; CHECK-NEXT:    vupklsw v3, v3
; CHECK-NEXT:    xxmrgld v2, v2, v3
; CHECK-NEXT:    mfvsrwz r6, v2
; CHECK-NEXT:    rldimi r5, r6, 32, 0
; CHECK-NEXT:    mtfprd f1, r5
; CHECK-NEXT:    li r5, 1
; CHECK-NEXT:    mtvsrd v3, r5
; CHECK-NEXT:    xxswapd vs0, v2
; CHECK-NEXT:    mffprwz r4, f0
; CHECK-NEXT:    lxvd2x vs0, 0, r7
; CHECK-NEXT:    mr r7, r4
; CHECK-NEXT:    rldimi r7, r3, 32, 0
; CHECK-NEXT:    mtfprd f2, r7
; CHECK-NEXT:    addis r7, r2, .LCPI0_1@toc@ha
; CHECK-NEXT:    addi r7, r7, .LCPI0_1@toc@l
; CHECK-NEXT:    vmrghh v3, v5, v3
; CHECK-NEXT:    xxswapd v5, vs0
; CHECK-NEXT:    xxmrghd v4, vs2, vs1
; CHECK-NEXT:    lxvd2x vs1, 0, r7
; CHECK-NEXT:    li r7, 0
; CHECK-NEXT:    rldimi r7, r5, 32, 0
; CHECK-NEXT:    mtfprd f0, r7
; CHECK-NEXT:    mr r7, r6
; CHECK-NEXT:    rldimi r7, r5, 32, 0
; CHECK-NEXT:    mtfprd f2, r7
; CHECK-NEXT:    mr r7, r6
; CHECK-NEXT:    xxmrglw v1, v4, v4
; CHECK-NEXT:    xxmrghw v6, v4, v4
; CHECK-NEXT:    rldimi r7, r3, 32, 0
; CHECK-NEXT:    rldimi r3, r6, 32, 0
; CHECK-NEXT:    rldimi r6, r4, 32, 0
; CHECK-NEXT:    mtfprd f3, r7
; CHECK-NEXT:    mr r7, r4
; CHECK-NEXT:    rldimi r4, r4, 32, 0
; CHECK-NEXT:    mtfprd f4, r6
; CHECK-NEXT:    rldimi r7, r5, 32, 0
; CHECK-NEXT:    rldimi r5, r5, 32, 0
; CHECK-NEXT:    xxswapd v0, vs1
; CHECK-NEXT:    xxspltw vs1, v3, 3
; CHECK-NEXT:    vperm v3, v1, v4, v5
; CHECK-NEXT:    vmrghh v4, v6, v4
; CHECK-NEXT:    vperm v2, v7, v2, v0
; CHECK-NEXT:    xxmrghd v5, vs3, vs2
; CHECK-NEXT:    mtfprd f3, r4
; CHECK-NEXT:    xxmrglw vs2, v4, v3
; CHECK-NEXT:    addis r4, r2, .LCPI0_2@toc@ha
; CHECK-NEXT:    addi r4, r4, .LCPI0_2@toc@l
; CHECK-NEXT:    xxmrghd v3, vs0, vs3
; CHECK-NEXT:    mtfprd f0, r7
; CHECK-NEXT:    mtfprd f3, r3
; CHECK-NEXT:    vpkuwum v3, v5, v3
; CHECK-NEXT:    xxmrghd v0, vs3, vs0
; CHECK-NEXT:    mtfprd f3, r5
; CHECK-NEXT:    xxmrghd v4, vs0, vs4
; CHECK-NEXT:    xxmrghd v1, vs3, vs0
; CHECK-NEXT:    lxvd2x vs0, 0, r4
; CHECK-NEXT:    vpkuwum v5, v0, v1
; CHECK-NEXT:    xxswapd v6, vs0
; CHECK-NEXT:    vperm v4, v4, v2, v6
; CHECK-NEXT:    xxmrgld v2, vs2, vs1
; CHECK-NEXT:    blr
entry:
  %0 = bitcast <8 x i8> %conv to i64
  %vecinit9 = insertelement <2 x i64> splat (i64 1), i64 %0, i64 1
  %shuffle = shufflevector <2 x i64> %vecinit9, <2 x i64> <i64 1, i64 0>, <32 x i32> <i32 2, i32 3, i32 2, i32 3, i32 2, i32 1, i32 0, i32 3, i32 0, i32 0, i32 3, i32 2, i32 1, i32 2, i32 1, i32 3, i32 0, i32 3, i32 3, i32 1, i32 1, i32 0, i32 0, i32 2, i32 0, i32 2, i32 2, i32 2, i32 0, i32 2, i32 3, i32 1>
  %conv11 = trunc <32 x i64> %shuffle to <32 x i16>
  ret <32 x i16> %conv11
}
