; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=i686-- -mattr=+sse2,+pclmul | FileCheck %s

; Minimal test for i686 PCLMULQDQ lowering

define i32 @clmul_i32(i32 %a, i32 %b) nounwind {
; CHECK-LABEL: clmul_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movd {{.*#+}} xmm0 = mem[0],zero,zero,zero
; CHECK-NEXT:    movd {{.*#+}} xmm1 = mem[0],zero,zero,zero
; CHECK-NEXT:    pclmulqdq $0, %xmm0, %xmm1
; CHECK-NEXT:    movd %xmm1, %eax
; CHECK-NEXT:    retl
  %res = call i32 @llvm.clmul.i32(i32 %a, i32 %b)
  ret i32 %res
}

define i64 @clmul_i64(i64 %a, i64 %b) nounwind {
; CHECK-LABEL: clmul_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq {{.*#+}} xmm0 = mem[0],zero
; CHECK-NEXT:    movq {{.*#+}} xmm1 = mem[0],zero
; CHECK-NEXT:    pclmulqdq $0, %xmm0, %xmm1
; CHECK-NEXT:    movd %xmm1, %eax
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm1[1,1,1,1]
; CHECK-NEXT:    movd %xmm0, %edx
; CHECK-NEXT:    retl
  %res = call i64 @llvm.clmul.i64(i64 %a, i64 %b)
  ret i64 %res
}

define i64 @clmulr_i64(i64 %a, i64 %b) nounwind {
; CHECK-LABEL: clmulr_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushl %esi
; CHECK-NEXT:    pxor %xmm1, %xmm1
; CHECK-NEXT:    movq {{.*#+}} xmm2 = mem[0],zero
; CHECK-NEXT:    movdqa %xmm2, %xmm3
; CHECK-NEXT:    pclmulqdq $0, %xmm1, %xmm3
; CHECK-NEXT:    movd %xmm3, %eax
; CHECK-NEXT:    movq {{.*#+}} xmm0 = mem[0],zero
; CHECK-NEXT:    pclmulqdq $0, %xmm0, %xmm1
; CHECK-NEXT:    movd %xmm1, %edx
; CHECK-NEXT:    xorl %eax, %edx
; CHECK-NEXT:    pclmulqdq $0, %xmm2, %xmm0
; CHECK-NEXT:    pshufd {{.*#+}} xmm2 = xmm0[2,3,2,3]
; CHECK-NEXT:    movd %xmm2, %ecx
; CHECK-NEXT:    xorl %edx, %ecx
; CHECK-NEXT:    pshufd {{.*#+}} xmm2 = xmm3[1,1,1,1]
; CHECK-NEXT:    movd %xmm2, %eax
; CHECK-NEXT:    pshufd {{.*#+}} xmm1 = xmm1[1,1,1,1]
; CHECK-NEXT:    movd %xmm1, %esi
; CHECK-NEXT:    xorl %eax, %esi
; CHECK-NEXT:    pshufd {{.*#+}} xmm1 = xmm0[3,3,3,3]
; CHECK-NEXT:    movd %xmm1, %edx
; CHECK-NEXT:    xorl %esi, %edx
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[1,1,1,1]
; CHECK-NEXT:    movd %xmm0, %eax
; CHECK-NEXT:    shldl $1, %ecx, %edx
; CHECK-NEXT:    shrdl $31, %ecx, %eax
; CHECK-NEXT:    popl %esi
; CHECK-NEXT:    retl
  %a.ext = zext i64 %a to i128
  %b.ext = zext i64 %b to i128
  %clmul = call i128 @llvm.clmul.i128(i128 %a.ext, i128 %b.ext)
  %res.ext = lshr i128 %clmul, 63
  %res = trunc i128 %res.ext to i64
  ret i64 %res
}

define i64 @clmulh_i64(i64 %a, i64 %b) nounwind {
; CHECK-LABEL: clmulh_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushl %esi
; CHECK-NEXT:    pxor %xmm0, %xmm0
; CHECK-NEXT:    movq {{.*#+}} xmm2 = mem[0],zero
; CHECK-NEXT:    movdqa %xmm2, %xmm3
; CHECK-NEXT:    pclmulqdq $0, %xmm0, %xmm3
; CHECK-NEXT:    movd %xmm3, %eax
; CHECK-NEXT:    movq {{.*#+}} xmm1 = mem[0],zero
; CHECK-NEXT:    pclmulqdq $0, %xmm1, %xmm0
; CHECK-NEXT:    movd %xmm0, %ecx
; CHECK-NEXT:    xorl %eax, %ecx
; CHECK-NEXT:    pclmulqdq $0, %xmm2, %xmm1
; CHECK-NEXT:    pshufd {{.*#+}} xmm2 = xmm1[2,3,2,3]
; CHECK-NEXT:    movd %xmm2, %eax
; CHECK-NEXT:    xorl %ecx, %eax
; CHECK-NEXT:    pshufd {{.*#+}} xmm2 = xmm3[1,1,1,1]
; CHECK-NEXT:    movd %xmm2, %ecx
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[1,1,1,1]
; CHECK-NEXT:    movd %xmm0, %esi
; CHECK-NEXT:    xorl %ecx, %esi
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm1[3,3,3,3]
; CHECK-NEXT:    movd %xmm0, %edx
; CHECK-NEXT:    xorl %esi, %edx
; CHECK-NEXT:    popl %esi
; CHECK-NEXT:    retl
  %a.ext = zext i64 %a to i128
  %b.ext = zext i64 %b to i128
  %clmul = call i128 @llvm.clmul.i128(i128 %a.ext, i128 %b.ext)
  %res.ext = lshr i128 %clmul, 64
  %res = trunc i128 %res.ext to i64
  ret i64 %res
}
