; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+sse2 | FileCheck %s --check-prefixes=SSE,SSE2
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+sse4.1 | FileCheck %s --check-prefixes=SSE,SSE4,SSE41
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+sse4.2 | FileCheck %s --check-prefixes=SSE,SSE4,SSE42
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx | FileCheck %s --check-prefixes=AVX,AVX1
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx2 | FileCheck %s --check-prefixes=AVX,AVX2
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx512f,+avx512bw | FileCheck %s --check-prefixes=AVX512,AVX512BW
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx512f,+avx512bw,+avx512vl | FileCheck %s --check-prefixes=AVX512,AVX512VL

;
; vXi64
;

define i64 @test_v2i64(<2 x i64> %a0) {
; SSE2-LABEL: test_v2i64:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movq %xmm0, %rcx
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[2,3,2,3]
; SSE2-NEXT:    movq %xmm0, %rax
; SSE2-NEXT:    cmpq %rax, %rcx
; SSE2-NEXT:    cmovlq %rcx, %rax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v2i64:
; SSE4:       # %bb.0:
; SSE4-NEXT:    pextrq $1, %xmm0, %rax
; SSE4-NEXT:    movq %xmm0, %rcx
; SSE4-NEXT:    cmpq %rax, %rcx
; SSE4-NEXT:    cmovlq %rcx, %rax
; SSE4-NEXT:    retq
;
; AVX-LABEL: test_v2i64:
; AVX:       # %bb.0:
; AVX-NEXT:    vpextrq $1, %xmm0, %rax
; AVX-NEXT:    vmovq %xmm0, %rcx
; AVX-NEXT:    cmpq %rax, %rcx
; AVX-NEXT:    cmovlq %rcx, %rax
; AVX-NEXT:    retq
;
; AVX512-LABEL: test_v2i64:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpextrq $1, %xmm0, %rax
; AVX512-NEXT:    vmovq %xmm0, %rcx
; AVX512-NEXT:    cmpq %rax, %rcx
; AVX512-NEXT:    cmovlq %rcx, %rax
; AVX512-NEXT:    retq
  %1 = call i64 @llvm.vector.reduce.smin.v2i64(<2 x i64> %a0)
  ret i64 %1
}

define i64 @test_v4i64(<4 x i64> %a0) {
; SSE2-LABEL: test_v4i64:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa {{.*#+}} xmm2 = [2147483648,2147483648]
; SSE2-NEXT:    movdqa %xmm0, %xmm3
; SSE2-NEXT:    pxor %xmm2, %xmm3
; SSE2-NEXT:    pxor %xmm1, %xmm2
; SSE2-NEXT:    movdqa %xmm2, %xmm4
; SSE2-NEXT:    pcmpgtd %xmm3, %xmm4
; SSE2-NEXT:    pshufd {{.*#+}} xmm5 = xmm4[0,0,2,2]
; SSE2-NEXT:    pcmpeqd %xmm3, %xmm2
; SSE2-NEXT:    pshufd {{.*#+}} xmm2 = xmm2[1,1,3,3]
; SSE2-NEXT:    pand %xmm5, %xmm2
; SSE2-NEXT:    pshufd {{.*#+}} xmm3 = xmm4[1,1,3,3]
; SSE2-NEXT:    por %xmm2, %xmm3
; SSE2-NEXT:    pand %xmm3, %xmm0
; SSE2-NEXT:    pandn %xmm1, %xmm3
; SSE2-NEXT:    por %xmm0, %xmm3
; SSE2-NEXT:    movq %xmm3, %rcx
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm3[2,3,2,3]
; SSE2-NEXT:    movq %xmm0, %rax
; SSE2-NEXT:    cmpq %rax, %rcx
; SSE2-NEXT:    cmovlq %rcx, %rax
; SSE2-NEXT:    retq
;
; SSE41-LABEL: test_v4i64:
; SSE41:       # %bb.0:
; SSE41-NEXT:    movdqa %xmm0, %xmm2
; SSE41-NEXT:    pmovzxdq {{.*#+}} xmm0 = [2147483648,2147483648]
; SSE41-NEXT:    movdqa %xmm2, %xmm3
; SSE41-NEXT:    pxor %xmm0, %xmm3
; SSE41-NEXT:    pxor %xmm1, %xmm0
; SSE41-NEXT:    movdqa %xmm0, %xmm4
; SSE41-NEXT:    pcmpgtd %xmm3, %xmm4
; SSE41-NEXT:    pshufd {{.*#+}} xmm5 = xmm4[0,0,2,2]
; SSE41-NEXT:    pcmpeqd %xmm3, %xmm0
; SSE41-NEXT:    pshufd {{.*#+}} xmm3 = xmm0[1,1,3,3]
; SSE41-NEXT:    pand %xmm5, %xmm3
; SSE41-NEXT:    pshufd {{.*#+}} xmm0 = xmm4[1,1,3,3]
; SSE41-NEXT:    por %xmm3, %xmm0
; SSE41-NEXT:    blendvpd %xmm0, %xmm2, %xmm1
; SSE41-NEXT:    pextrq $1, %xmm1, %rax
; SSE41-NEXT:    movq %xmm1, %rcx
; SSE41-NEXT:    cmpq %rax, %rcx
; SSE41-NEXT:    cmovlq %rcx, %rax
; SSE41-NEXT:    retq
;
; SSE42-LABEL: test_v4i64:
; SSE42:       # %bb.0:
; SSE42-NEXT:    movdqa %xmm0, %xmm2
; SSE42-NEXT:    movdqa %xmm1, %xmm0
; SSE42-NEXT:    pcmpgtq %xmm2, %xmm0
; SSE42-NEXT:    blendvpd %xmm0, %xmm2, %xmm1
; SSE42-NEXT:    pextrq $1, %xmm1, %rax
; SSE42-NEXT:    movq %xmm1, %rcx
; SSE42-NEXT:    cmpq %rax, %rcx
; SSE42-NEXT:    cmovlq %rcx, %rax
; SSE42-NEXT:    retq
;
; AVX1-LABEL: test_v4i64:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm1
; AVX1-NEXT:    vpcmpgtq %xmm0, %xmm1, %xmm2
; AVX1-NEXT:    vblendvpd %xmm2, %xmm0, %xmm1, %xmm0
; AVX1-NEXT:    vpextrq $1, %xmm0, %rax
; AVX1-NEXT:    vmovq %xmm0, %rcx
; AVX1-NEXT:    cmpq %rax, %rcx
; AVX1-NEXT:    cmovlq %rcx, %rax
; AVX1-NEXT:    vzeroupper
; AVX1-NEXT:    retq
;
; AVX2-LABEL: test_v4i64:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpcmpgtq %xmm0, %xmm1, %xmm2
; AVX2-NEXT:    vblendvpd %xmm2, %xmm0, %xmm1, %xmm0
; AVX2-NEXT:    vpextrq $1, %xmm0, %rax
; AVX2-NEXT:    vmovq %xmm0, %rcx
; AVX2-NEXT:    cmpq %rax, %rcx
; AVX2-NEXT:    cmovlq %rcx, %rax
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512BW-LABEL: test_v4i64:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    # kill: def $ymm0 killed $ymm0 def $zmm0
; AVX512BW-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512BW-NEXT:    vpminsq %zmm1, %zmm0, %zmm0
; AVX512BW-NEXT:    vpextrq $1, %xmm0, %rax
; AVX512BW-NEXT:    vmovq %xmm0, %rcx
; AVX512BW-NEXT:    cmpq %rax, %rcx
; AVX512BW-NEXT:    cmovlq %rcx, %rax
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v4i64:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512VL-NEXT:    vpminsq %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vpextrq $1, %xmm0, %rax
; AVX512VL-NEXT:    vmovq %xmm0, %rcx
; AVX512VL-NEXT:    cmpq %rax, %rcx
; AVX512VL-NEXT:    cmovlq %rcx, %rax
; AVX512VL-NEXT:    vzeroupper
; AVX512VL-NEXT:    retq
  %1 = call i64 @llvm.vector.reduce.smin.v4i64(<4 x i64> %a0)
  ret i64 %1
}

define i64 @test_v8i64(<8 x i64> %a0) {
; SSE2-LABEL: test_v8i64:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa {{.*#+}} xmm4 = [2147483648,2147483648]
; SSE2-NEXT:    movdqa %xmm0, %xmm5
; SSE2-NEXT:    pxor %xmm4, %xmm5
; SSE2-NEXT:    movdqa %xmm2, %xmm6
; SSE2-NEXT:    pxor %xmm4, %xmm6
; SSE2-NEXT:    movdqa %xmm6, %xmm7
; SSE2-NEXT:    pcmpgtd %xmm5, %xmm7
; SSE2-NEXT:    pshufd {{.*#+}} xmm8 = xmm7[0,0,2,2]
; SSE2-NEXT:    pcmpeqd %xmm5, %xmm6
; SSE2-NEXT:    pshufd {{.*#+}} xmm6 = xmm6[1,1,3,3]
; SSE2-NEXT:    pand %xmm8, %xmm6
; SSE2-NEXT:    pshufd {{.*#+}} xmm5 = xmm7[1,1,3,3]
; SSE2-NEXT:    por %xmm6, %xmm5
; SSE2-NEXT:    pand %xmm5, %xmm0
; SSE2-NEXT:    pandn %xmm2, %xmm5
; SSE2-NEXT:    por %xmm0, %xmm5
; SSE2-NEXT:    movdqa %xmm5, %xmm0
; SSE2-NEXT:    pxor %xmm4, %xmm0
; SSE2-NEXT:    movdqa %xmm1, %xmm2
; SSE2-NEXT:    pxor %xmm4, %xmm2
; SSE2-NEXT:    movdqa %xmm3, %xmm6
; SSE2-NEXT:    pxor %xmm4, %xmm6
; SSE2-NEXT:    movdqa %xmm6, %xmm7
; SSE2-NEXT:    pcmpgtd %xmm2, %xmm7
; SSE2-NEXT:    pshufd {{.*#+}} xmm8 = xmm7[0,0,2,2]
; SSE2-NEXT:    pcmpeqd %xmm2, %xmm6
; SSE2-NEXT:    pshufd {{.*#+}} xmm2 = xmm6[1,1,3,3]
; SSE2-NEXT:    pand %xmm8, %xmm2
; SSE2-NEXT:    pshufd {{.*#+}} xmm6 = xmm7[1,1,3,3]
; SSE2-NEXT:    por %xmm2, %xmm6
; SSE2-NEXT:    pand %xmm6, %xmm1
; SSE2-NEXT:    pandn %xmm3, %xmm6
; SSE2-NEXT:    por %xmm1, %xmm6
; SSE2-NEXT:    pxor %xmm6, %xmm4
; SSE2-NEXT:    movdqa %xmm4, %xmm1
; SSE2-NEXT:    pcmpgtd %xmm0, %xmm1
; SSE2-NEXT:    pshufd {{.*#+}} xmm2 = xmm1[0,0,2,2]
; SSE2-NEXT:    pcmpeqd %xmm0, %xmm4
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm4[1,1,3,3]
; SSE2-NEXT:    pand %xmm2, %xmm0
; SSE2-NEXT:    pshufd {{.*#+}} xmm1 = xmm1[1,1,3,3]
; SSE2-NEXT:    por %xmm0, %xmm1
; SSE2-NEXT:    pand %xmm1, %xmm5
; SSE2-NEXT:    pandn %xmm6, %xmm1
; SSE2-NEXT:    por %xmm5, %xmm1
; SSE2-NEXT:    movq %xmm1, %rcx
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm1[2,3,2,3]
; SSE2-NEXT:    movq %xmm0, %rax
; SSE2-NEXT:    cmpq %rax, %rcx
; SSE2-NEXT:    cmovlq %rcx, %rax
; SSE2-NEXT:    retq
;
; SSE41-LABEL: test_v8i64:
; SSE41:       # %bb.0:
; SSE41-NEXT:    movdqa %xmm0, %xmm4
; SSE41-NEXT:    pmovzxdq {{.*#+}} xmm5 = [2147483648,2147483648]
; SSE41-NEXT:    pxor %xmm5, %xmm0
; SSE41-NEXT:    movdqa %xmm2, %xmm6
; SSE41-NEXT:    pxor %xmm5, %xmm6
; SSE41-NEXT:    movdqa %xmm6, %xmm7
; SSE41-NEXT:    pcmpgtd %xmm0, %xmm7
; SSE41-NEXT:    pshufd {{.*#+}} xmm8 = xmm7[0,0,2,2]
; SSE41-NEXT:    pcmpeqd %xmm0, %xmm6
; SSE41-NEXT:    pshufd {{.*#+}} xmm6 = xmm6[1,1,3,3]
; SSE41-NEXT:    pand %xmm8, %xmm6
; SSE41-NEXT:    pshufd {{.*#+}} xmm0 = xmm7[1,1,3,3]
; SSE41-NEXT:    por %xmm6, %xmm0
; SSE41-NEXT:    blendvpd %xmm0, %xmm4, %xmm2
; SSE41-NEXT:    movapd %xmm2, %xmm4
; SSE41-NEXT:    xorpd %xmm5, %xmm4
; SSE41-NEXT:    movdqa %xmm1, %xmm0
; SSE41-NEXT:    pxor %xmm5, %xmm0
; SSE41-NEXT:    movdqa %xmm3, %xmm6
; SSE41-NEXT:    pxor %xmm5, %xmm6
; SSE41-NEXT:    movdqa %xmm6, %xmm7
; SSE41-NEXT:    pcmpgtd %xmm0, %xmm7
; SSE41-NEXT:    pshufd {{.*#+}} xmm8 = xmm7[0,0,2,2]
; SSE41-NEXT:    pcmpeqd %xmm0, %xmm6
; SSE41-NEXT:    pshufd {{.*#+}} xmm6 = xmm6[1,1,3,3]
; SSE41-NEXT:    pand %xmm8, %xmm6
; SSE41-NEXT:    pshufd {{.*#+}} xmm0 = xmm7[1,1,3,3]
; SSE41-NEXT:    por %xmm6, %xmm0
; SSE41-NEXT:    blendvpd %xmm0, %xmm1, %xmm3
; SSE41-NEXT:    xorpd %xmm3, %xmm5
; SSE41-NEXT:    movapd %xmm5, %xmm0
; SSE41-NEXT:    pcmpgtd %xmm4, %xmm0
; SSE41-NEXT:    pshufd {{.*#+}} xmm1 = xmm0[0,0,2,2]
; SSE41-NEXT:    pcmpeqd %xmm4, %xmm5
; SSE41-NEXT:    pshufd {{.*#+}} xmm4 = xmm5[1,1,3,3]
; SSE41-NEXT:    pand %xmm1, %xmm4
; SSE41-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[1,1,3,3]
; SSE41-NEXT:    por %xmm4, %xmm0
; SSE41-NEXT:    blendvpd %xmm0, %xmm2, %xmm3
; SSE41-NEXT:    pextrq $1, %xmm3, %rax
; SSE41-NEXT:    movq %xmm3, %rcx
; SSE41-NEXT:    cmpq %rax, %rcx
; SSE41-NEXT:    cmovlq %rcx, %rax
; SSE41-NEXT:    retq
;
; SSE42-LABEL: test_v8i64:
; SSE42:       # %bb.0:
; SSE42-NEXT:    movdqa %xmm0, %xmm4
; SSE42-NEXT:    movdqa %xmm2, %xmm0
; SSE42-NEXT:    pcmpgtq %xmm4, %xmm0
; SSE42-NEXT:    blendvpd %xmm0, %xmm4, %xmm2
; SSE42-NEXT:    movdqa %xmm3, %xmm0
; SSE42-NEXT:    pcmpgtq %xmm1, %xmm0
; SSE42-NEXT:    blendvpd %xmm0, %xmm1, %xmm3
; SSE42-NEXT:    movapd %xmm3, %xmm0
; SSE42-NEXT:    pcmpgtq %xmm2, %xmm0
; SSE42-NEXT:    blendvpd %xmm0, %xmm2, %xmm3
; SSE42-NEXT:    pextrq $1, %xmm3, %rax
; SSE42-NEXT:    movq %xmm3, %rcx
; SSE42-NEXT:    cmpq %rax, %rcx
; SSE42-NEXT:    cmovlq %rcx, %rax
; SSE42-NEXT:    retq
;
; AVX1-LABEL: test_v8i64:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vpcmpgtq %xmm0, %xmm1, %xmm2
; AVX1-NEXT:    vblendvpd %xmm2, %xmm0, %xmm1, %xmm2
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm1
; AVX1-NEXT:    vpcmpgtq %xmm0, %xmm1, %xmm3
; AVX1-NEXT:    vblendvpd %xmm3, %xmm0, %xmm1, %xmm0
; AVX1-NEXT:    vpcmpgtq %xmm2, %xmm0, %xmm1
; AVX1-NEXT:    vblendvpd %xmm1, %xmm2, %xmm0, %xmm0
; AVX1-NEXT:    vpextrq $1, %xmm0, %rax
; AVX1-NEXT:    vmovq %xmm0, %rcx
; AVX1-NEXT:    cmpq %rax, %rcx
; AVX1-NEXT:    cmovlq %rcx, %rax
; AVX1-NEXT:    vzeroupper
; AVX1-NEXT:    retq
;
; AVX2-LABEL: test_v8i64:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpcmpgtq %ymm0, %ymm1, %ymm2
; AVX2-NEXT:    vblendvpd %ymm2, %ymm0, %ymm1, %ymm0
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpcmpgtq %xmm0, %xmm1, %xmm2
; AVX2-NEXT:    vblendvpd %xmm2, %xmm0, %xmm1, %xmm0
; AVX2-NEXT:    vpextrq $1, %xmm0, %rax
; AVX2-NEXT:    vmovq %xmm0, %rcx
; AVX2-NEXT:    cmpq %rax, %rcx
; AVX2-NEXT:    cmovlq %rcx, %rax
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512BW-LABEL: test_v8i64:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vextracti64x4 $1, %zmm0, %ymm1
; AVX512BW-NEXT:    vpminsq %zmm1, %zmm0, %zmm0
; AVX512BW-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512BW-NEXT:    vpminsq %zmm1, %zmm0, %zmm0
; AVX512BW-NEXT:    vpextrq $1, %xmm0, %rax
; AVX512BW-NEXT:    vmovq %xmm0, %rcx
; AVX512BW-NEXT:    cmpq %rax, %rcx
; AVX512BW-NEXT:    cmovlq %rcx, %rax
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v8i64:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    vextracti64x4 $1, %zmm0, %ymm1
; AVX512VL-NEXT:    vpminsq %ymm1, %ymm0, %ymm0
; AVX512VL-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512VL-NEXT:    vpminsq %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vpextrq $1, %xmm0, %rax
; AVX512VL-NEXT:    vmovq %xmm0, %rcx
; AVX512VL-NEXT:    cmpq %rax, %rcx
; AVX512VL-NEXT:    cmovlq %rcx, %rax
; AVX512VL-NEXT:    vzeroupper
; AVX512VL-NEXT:    retq
  %1 = call i64 @llvm.vector.reduce.smin.v8i64(<8 x i64> %a0)
  ret i64 %1
}

define i64 @test_v16i64(<16 x i64> %a0) {
; SSE2-LABEL: test_v16i64:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa {{.*#+}} xmm8 = [2147483648,2147483648]
; SSE2-NEXT:    movdqa %xmm0, %xmm9
; SSE2-NEXT:    pxor %xmm8, %xmm9
; SSE2-NEXT:    movdqa %xmm4, %xmm10
; SSE2-NEXT:    pxor %xmm8, %xmm10
; SSE2-NEXT:    movdqa %xmm10, %xmm11
; SSE2-NEXT:    pcmpgtd %xmm9, %xmm11
; SSE2-NEXT:    pshufd {{.*#+}} xmm12 = xmm11[0,0,2,2]
; SSE2-NEXT:    pcmpeqd %xmm9, %xmm10
; SSE2-NEXT:    pshufd {{.*#+}} xmm10 = xmm10[1,1,3,3]
; SSE2-NEXT:    pand %xmm12, %xmm10
; SSE2-NEXT:    pshufd {{.*#+}} xmm9 = xmm11[1,1,3,3]
; SSE2-NEXT:    por %xmm10, %xmm9
; SSE2-NEXT:    pand %xmm9, %xmm0
; SSE2-NEXT:    pandn %xmm4, %xmm9
; SSE2-NEXT:    por %xmm0, %xmm9
; SSE2-NEXT:    movdqa %xmm9, %xmm0
; SSE2-NEXT:    pxor %xmm8, %xmm0
; SSE2-NEXT:    movdqa %xmm2, %xmm4
; SSE2-NEXT:    pxor %xmm8, %xmm4
; SSE2-NEXT:    movdqa %xmm6, %xmm10
; SSE2-NEXT:    pxor %xmm8, %xmm10
; SSE2-NEXT:    movdqa %xmm10, %xmm11
; SSE2-NEXT:    pcmpgtd %xmm4, %xmm11
; SSE2-NEXT:    pshufd {{.*#+}} xmm12 = xmm11[0,0,2,2]
; SSE2-NEXT:    pcmpeqd %xmm4, %xmm10
; SSE2-NEXT:    pshufd {{.*#+}} xmm4 = xmm10[1,1,3,3]
; SSE2-NEXT:    pand %xmm12, %xmm4
; SSE2-NEXT:    pshufd {{.*#+}} xmm10 = xmm11[1,1,3,3]
; SSE2-NEXT:    por %xmm4, %xmm10
; SSE2-NEXT:    pand %xmm10, %xmm2
; SSE2-NEXT:    pandn %xmm6, %xmm10
; SSE2-NEXT:    por %xmm2, %xmm10
; SSE2-NEXT:    movdqa %xmm10, %xmm2
; SSE2-NEXT:    pxor %xmm8, %xmm2
; SSE2-NEXT:    movdqa %xmm2, %xmm4
; SSE2-NEXT:    pcmpgtd %xmm0, %xmm4
; SSE2-NEXT:    pshufd {{.*#+}} xmm6 = xmm4[0,0,2,2]
; SSE2-NEXT:    pcmpeqd %xmm0, %xmm2
; SSE2-NEXT:    pshufd {{.*#+}} xmm2 = xmm2[1,1,3,3]
; SSE2-NEXT:    pand %xmm6, %xmm2
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm4[1,1,3,3]
; SSE2-NEXT:    por %xmm2, %xmm0
; SSE2-NEXT:    pand %xmm0, %xmm9
; SSE2-NEXT:    pandn %xmm10, %xmm0
; SSE2-NEXT:    por %xmm9, %xmm0
; SSE2-NEXT:    movdqa %xmm0, %xmm2
; SSE2-NEXT:    pxor %xmm8, %xmm2
; SSE2-NEXT:    movdqa %xmm1, %xmm4
; SSE2-NEXT:    pxor %xmm8, %xmm4
; SSE2-NEXT:    movdqa %xmm5, %xmm6
; SSE2-NEXT:    pxor %xmm8, %xmm6
; SSE2-NEXT:    movdqa %xmm6, %xmm9
; SSE2-NEXT:    pcmpgtd %xmm4, %xmm9
; SSE2-NEXT:    pshufd {{.*#+}} xmm10 = xmm9[0,0,2,2]
; SSE2-NEXT:    pcmpeqd %xmm4, %xmm6
; SSE2-NEXT:    pshufd {{.*#+}} xmm6 = xmm6[1,1,3,3]
; SSE2-NEXT:    pand %xmm10, %xmm6
; SSE2-NEXT:    pshufd {{.*#+}} xmm4 = xmm9[1,1,3,3]
; SSE2-NEXT:    por %xmm6, %xmm4
; SSE2-NEXT:    pand %xmm4, %xmm1
; SSE2-NEXT:    pandn %xmm5, %xmm4
; SSE2-NEXT:    por %xmm1, %xmm4
; SSE2-NEXT:    movdqa %xmm4, %xmm1
; SSE2-NEXT:    pxor %xmm8, %xmm1
; SSE2-NEXT:    movdqa %xmm3, %xmm5
; SSE2-NEXT:    pxor %xmm8, %xmm5
; SSE2-NEXT:    movdqa %xmm7, %xmm6
; SSE2-NEXT:    pxor %xmm8, %xmm6
; SSE2-NEXT:    movdqa %xmm6, %xmm9
; SSE2-NEXT:    pcmpgtd %xmm5, %xmm9
; SSE2-NEXT:    pshufd {{.*#+}} xmm10 = xmm9[0,0,2,2]
; SSE2-NEXT:    pcmpeqd %xmm5, %xmm6
; SSE2-NEXT:    pshufd {{.*#+}} xmm5 = xmm6[1,1,3,3]
; SSE2-NEXT:    pand %xmm10, %xmm5
; SSE2-NEXT:    pshufd {{.*#+}} xmm6 = xmm9[1,1,3,3]
; SSE2-NEXT:    por %xmm5, %xmm6
; SSE2-NEXT:    pand %xmm6, %xmm3
; SSE2-NEXT:    pandn %xmm7, %xmm6
; SSE2-NEXT:    por %xmm3, %xmm6
; SSE2-NEXT:    movdqa %xmm6, %xmm3
; SSE2-NEXT:    pxor %xmm8, %xmm3
; SSE2-NEXT:    movdqa %xmm3, %xmm5
; SSE2-NEXT:    pcmpgtd %xmm1, %xmm5
; SSE2-NEXT:    pshufd {{.*#+}} xmm7 = xmm5[0,0,2,2]
; SSE2-NEXT:    pcmpeqd %xmm1, %xmm3
; SSE2-NEXT:    pshufd {{.*#+}} xmm1 = xmm3[1,1,3,3]
; SSE2-NEXT:    pand %xmm7, %xmm1
; SSE2-NEXT:    pshufd {{.*#+}} xmm3 = xmm5[1,1,3,3]
; SSE2-NEXT:    por %xmm1, %xmm3
; SSE2-NEXT:    pand %xmm3, %xmm4
; SSE2-NEXT:    pandn %xmm6, %xmm3
; SSE2-NEXT:    por %xmm4, %xmm3
; SSE2-NEXT:    pxor %xmm3, %xmm8
; SSE2-NEXT:    movdqa %xmm8, %xmm1
; SSE2-NEXT:    pcmpgtd %xmm2, %xmm1
; SSE2-NEXT:    pshufd {{.*#+}} xmm4 = xmm1[0,0,2,2]
; SSE2-NEXT:    pcmpeqd %xmm2, %xmm8
; SSE2-NEXT:    pshufd {{.*#+}} xmm2 = xmm8[1,1,3,3]
; SSE2-NEXT:    pand %xmm4, %xmm2
; SSE2-NEXT:    pshufd {{.*#+}} xmm1 = xmm1[1,1,3,3]
; SSE2-NEXT:    por %xmm2, %xmm1
; SSE2-NEXT:    pand %xmm1, %xmm0
; SSE2-NEXT:    pandn %xmm3, %xmm1
; SSE2-NEXT:    por %xmm0, %xmm1
; SSE2-NEXT:    movq %xmm1, %rcx
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm1[2,3,2,3]
; SSE2-NEXT:    movq %xmm0, %rax
; SSE2-NEXT:    cmpq %rax, %rcx
; SSE2-NEXT:    cmovlq %rcx, %rax
; SSE2-NEXT:    retq
;
; SSE41-LABEL: test_v16i64:
; SSE41:       # %bb.0:
; SSE41-NEXT:    movdqa %xmm0, %xmm8
; SSE41-NEXT:    pmovzxdq {{.*#+}} xmm9 = [2147483648,2147483648]
; SSE41-NEXT:    pxor %xmm9, %xmm0
; SSE41-NEXT:    movdqa %xmm4, %xmm10
; SSE41-NEXT:    pxor %xmm9, %xmm10
; SSE41-NEXT:    movdqa %xmm10, %xmm11
; SSE41-NEXT:    pcmpgtd %xmm0, %xmm11
; SSE41-NEXT:    pshufd {{.*#+}} xmm12 = xmm11[0,0,2,2]
; SSE41-NEXT:    pcmpeqd %xmm0, %xmm10
; SSE41-NEXT:    pshufd {{.*#+}} xmm10 = xmm10[1,1,3,3]
; SSE41-NEXT:    pand %xmm12, %xmm10
; SSE41-NEXT:    pshufd {{.*#+}} xmm0 = xmm11[1,1,3,3]
; SSE41-NEXT:    por %xmm10, %xmm0
; SSE41-NEXT:    blendvpd %xmm0, %xmm8, %xmm4
; SSE41-NEXT:    movapd %xmm4, %xmm8
; SSE41-NEXT:    xorpd %xmm9, %xmm8
; SSE41-NEXT:    movdqa %xmm2, %xmm0
; SSE41-NEXT:    pxor %xmm9, %xmm0
; SSE41-NEXT:    movdqa %xmm6, %xmm10
; SSE41-NEXT:    pxor %xmm9, %xmm10
; SSE41-NEXT:    movdqa %xmm10, %xmm11
; SSE41-NEXT:    pcmpgtd %xmm0, %xmm11
; SSE41-NEXT:    pshufd {{.*#+}} xmm12 = xmm11[0,0,2,2]
; SSE41-NEXT:    pcmpeqd %xmm0, %xmm10
; SSE41-NEXT:    pshufd {{.*#+}} xmm10 = xmm10[1,1,3,3]
; SSE41-NEXT:    pand %xmm12, %xmm10
; SSE41-NEXT:    pshufd {{.*#+}} xmm0 = xmm11[1,1,3,3]
; SSE41-NEXT:    por %xmm10, %xmm0
; SSE41-NEXT:    blendvpd %xmm0, %xmm2, %xmm6
; SSE41-NEXT:    movapd %xmm6, %xmm0
; SSE41-NEXT:    xorpd %xmm9, %xmm0
; SSE41-NEXT:    movapd %xmm0, %xmm2
; SSE41-NEXT:    pcmpgtd %xmm8, %xmm2
; SSE41-NEXT:    pshufd {{.*#+}} xmm10 = xmm2[0,0,2,2]
; SSE41-NEXT:    pcmpeqd %xmm8, %xmm0
; SSE41-NEXT:    pshufd {{.*#+}} xmm8 = xmm0[1,1,3,3]
; SSE41-NEXT:    pand %xmm10, %xmm8
; SSE41-NEXT:    pshufd {{.*#+}} xmm0 = xmm2[1,1,3,3]
; SSE41-NEXT:    por %xmm8, %xmm0
; SSE41-NEXT:    blendvpd %xmm0, %xmm4, %xmm6
; SSE41-NEXT:    movapd %xmm6, %xmm2
; SSE41-NEXT:    xorpd %xmm9, %xmm2
; SSE41-NEXT:    movdqa %xmm1, %xmm0
; SSE41-NEXT:    pxor %xmm9, %xmm0
; SSE41-NEXT:    movdqa %xmm5, %xmm4
; SSE41-NEXT:    pxor %xmm9, %xmm4
; SSE41-NEXT:    movdqa %xmm4, %xmm8
; SSE41-NEXT:    pcmpgtd %xmm0, %xmm8
; SSE41-NEXT:    pshufd {{.*#+}} xmm10 = xmm8[0,0,2,2]
; SSE41-NEXT:    pcmpeqd %xmm0, %xmm4
; SSE41-NEXT:    pshufd {{.*#+}} xmm4 = xmm4[1,1,3,3]
; SSE41-NEXT:    pand %xmm10, %xmm4
; SSE41-NEXT:    pshufd {{.*#+}} xmm0 = xmm8[1,1,3,3]
; SSE41-NEXT:    por %xmm4, %xmm0
; SSE41-NEXT:    blendvpd %xmm0, %xmm1, %xmm5
; SSE41-NEXT:    movapd %xmm5, %xmm1
; SSE41-NEXT:    xorpd %xmm9, %xmm1
; SSE41-NEXT:    movdqa %xmm3, %xmm0
; SSE41-NEXT:    pxor %xmm9, %xmm0
; SSE41-NEXT:    movdqa %xmm7, %xmm4
; SSE41-NEXT:    pxor %xmm9, %xmm4
; SSE41-NEXT:    movdqa %xmm4, %xmm8
; SSE41-NEXT:    pcmpgtd %xmm0, %xmm8
; SSE41-NEXT:    pshufd {{.*#+}} xmm10 = xmm8[0,0,2,2]
; SSE41-NEXT:    pcmpeqd %xmm0, %xmm4
; SSE41-NEXT:    pshufd {{.*#+}} xmm4 = xmm4[1,1,3,3]
; SSE41-NEXT:    pand %xmm10, %xmm4
; SSE41-NEXT:    pshufd {{.*#+}} xmm0 = xmm8[1,1,3,3]
; SSE41-NEXT:    por %xmm4, %xmm0
; SSE41-NEXT:    blendvpd %xmm0, %xmm3, %xmm7
; SSE41-NEXT:    movapd %xmm7, %xmm0
; SSE41-NEXT:    xorpd %xmm9, %xmm0
; SSE41-NEXT:    movapd %xmm0, %xmm3
; SSE41-NEXT:    pcmpgtd %xmm1, %xmm3
; SSE41-NEXT:    pshufd {{.*#+}} xmm4 = xmm3[0,0,2,2]
; SSE41-NEXT:    pcmpeqd %xmm1, %xmm0
; SSE41-NEXT:    pshufd {{.*#+}} xmm1 = xmm0[1,1,3,3]
; SSE41-NEXT:    pand %xmm4, %xmm1
; SSE41-NEXT:    pshufd {{.*#+}} xmm0 = xmm3[1,1,3,3]
; SSE41-NEXT:    por %xmm1, %xmm0
; SSE41-NEXT:    blendvpd %xmm0, %xmm5, %xmm7
; SSE41-NEXT:    xorpd %xmm7, %xmm9
; SSE41-NEXT:    movapd %xmm9, %xmm0
; SSE41-NEXT:    pcmpgtd %xmm2, %xmm0
; SSE41-NEXT:    pshufd {{.*#+}} xmm1 = xmm0[0,0,2,2]
; SSE41-NEXT:    pcmpeqd %xmm2, %xmm9
; SSE41-NEXT:    pshufd {{.*#+}} xmm2 = xmm9[1,1,3,3]
; SSE41-NEXT:    pand %xmm1, %xmm2
; SSE41-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[1,1,3,3]
; SSE41-NEXT:    por %xmm2, %xmm0
; SSE41-NEXT:    blendvpd %xmm0, %xmm6, %xmm7
; SSE41-NEXT:    pextrq $1, %xmm7, %rax
; SSE41-NEXT:    movq %xmm7, %rcx
; SSE41-NEXT:    cmpq %rax, %rcx
; SSE41-NEXT:    cmovlq %rcx, %rax
; SSE41-NEXT:    retq
;
; SSE42-LABEL: test_v16i64:
; SSE42:       # %bb.0:
; SSE42-NEXT:    movdqa %xmm0, %xmm8
; SSE42-NEXT:    movdqa %xmm4, %xmm0
; SSE42-NEXT:    pcmpgtq %xmm8, %xmm0
; SSE42-NEXT:    blendvpd %xmm0, %xmm8, %xmm4
; SSE42-NEXT:    movdqa %xmm6, %xmm0
; SSE42-NEXT:    pcmpgtq %xmm2, %xmm0
; SSE42-NEXT:    blendvpd %xmm0, %xmm2, %xmm6
; SSE42-NEXT:    movapd %xmm6, %xmm0
; SSE42-NEXT:    pcmpgtq %xmm4, %xmm0
; SSE42-NEXT:    blendvpd %xmm0, %xmm4, %xmm6
; SSE42-NEXT:    movdqa %xmm5, %xmm0
; SSE42-NEXT:    pcmpgtq %xmm1, %xmm0
; SSE42-NEXT:    blendvpd %xmm0, %xmm1, %xmm5
; SSE42-NEXT:    movdqa %xmm7, %xmm0
; SSE42-NEXT:    pcmpgtq %xmm3, %xmm0
; SSE42-NEXT:    blendvpd %xmm0, %xmm3, %xmm7
; SSE42-NEXT:    movapd %xmm7, %xmm0
; SSE42-NEXT:    pcmpgtq %xmm5, %xmm0
; SSE42-NEXT:    blendvpd %xmm0, %xmm5, %xmm7
; SSE42-NEXT:    movapd %xmm7, %xmm0
; SSE42-NEXT:    pcmpgtq %xmm6, %xmm0
; SSE42-NEXT:    blendvpd %xmm0, %xmm6, %xmm7
; SSE42-NEXT:    pextrq $1, %xmm7, %rax
; SSE42-NEXT:    movq %xmm7, %rcx
; SSE42-NEXT:    cmpq %rax, %rcx
; SSE42-NEXT:    cmovlq %rcx, %rax
; SSE42-NEXT:    retq
;
; AVX1-LABEL: test_v16i64:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vpcmpgtq %xmm0, %xmm2, %xmm4
; AVX1-NEXT:    vblendvpd %xmm4, %xmm0, %xmm2, %xmm4
; AVX1-NEXT:    vpcmpgtq %xmm1, %xmm3, %xmm5
; AVX1-NEXT:    vblendvpd %xmm5, %xmm1, %xmm3, %xmm5
; AVX1-NEXT:    vpcmpgtq %xmm4, %xmm5, %xmm6
; AVX1-NEXT:    vblendvpd %xmm6, %xmm4, %xmm5, %xmm4
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX1-NEXT:    vextractf128 $1, %ymm2, %xmm2
; AVX1-NEXT:    vpcmpgtq %xmm0, %xmm2, %xmm5
; AVX1-NEXT:    vblendvpd %xmm5, %xmm0, %xmm2, %xmm0
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm1
; AVX1-NEXT:    vextractf128 $1, %ymm3, %xmm2
; AVX1-NEXT:    vpcmpgtq %xmm1, %xmm2, %xmm3
; AVX1-NEXT:    vblendvpd %xmm3, %xmm1, %xmm2, %xmm1
; AVX1-NEXT:    vpcmpgtq %xmm0, %xmm1, %xmm2
; AVX1-NEXT:    vblendvpd %xmm2, %xmm0, %xmm1, %xmm0
; AVX1-NEXT:    vpcmpgtq %xmm4, %xmm0, %xmm1
; AVX1-NEXT:    vblendvpd %xmm1, %xmm4, %xmm0, %xmm0
; AVX1-NEXT:    vpextrq $1, %xmm0, %rax
; AVX1-NEXT:    vmovq %xmm0, %rcx
; AVX1-NEXT:    cmpq %rax, %rcx
; AVX1-NEXT:    cmovlq %rcx, %rax
; AVX1-NEXT:    vzeroupper
; AVX1-NEXT:    retq
;
; AVX2-LABEL: test_v16i64:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpcmpgtq %ymm0, %ymm2, %ymm4
; AVX2-NEXT:    vblendvpd %ymm4, %ymm0, %ymm2, %ymm0
; AVX2-NEXT:    vpcmpgtq %ymm1, %ymm3, %ymm2
; AVX2-NEXT:    vblendvpd %ymm2, %ymm1, %ymm3, %ymm1
; AVX2-NEXT:    vpcmpgtq %ymm0, %ymm1, %ymm2
; AVX2-NEXT:    vblendvpd %ymm2, %ymm0, %ymm1, %ymm0
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpcmpgtq %xmm0, %xmm1, %xmm2
; AVX2-NEXT:    vblendvpd %xmm2, %xmm0, %xmm1, %xmm0
; AVX2-NEXT:    vpextrq $1, %xmm0, %rax
; AVX2-NEXT:    vmovq %xmm0, %rcx
; AVX2-NEXT:    cmpq %rax, %rcx
; AVX2-NEXT:    cmovlq %rcx, %rax
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512BW-LABEL: test_v16i64:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vpminsq %zmm1, %zmm0, %zmm0
; AVX512BW-NEXT:    vextracti64x4 $1, %zmm0, %ymm1
; AVX512BW-NEXT:    vpminsq %zmm1, %zmm0, %zmm0
; AVX512BW-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512BW-NEXT:    vpminsq %zmm1, %zmm0, %zmm0
; AVX512BW-NEXT:    vpextrq $1, %xmm0, %rax
; AVX512BW-NEXT:    vmovq %xmm0, %rcx
; AVX512BW-NEXT:    cmpq %rax, %rcx
; AVX512BW-NEXT:    cmovlq %rcx, %rax
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v16i64:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    vpminsq %zmm1, %zmm0, %zmm0
; AVX512VL-NEXT:    vextracti64x4 $1, %zmm0, %ymm1
; AVX512VL-NEXT:    vpminsq %ymm1, %ymm0, %ymm0
; AVX512VL-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512VL-NEXT:    vpminsq %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vpextrq $1, %xmm0, %rax
; AVX512VL-NEXT:    vmovq %xmm0, %rcx
; AVX512VL-NEXT:    cmpq %rax, %rcx
; AVX512VL-NEXT:    cmovlq %rcx, %rax
; AVX512VL-NEXT:    vzeroupper
; AVX512VL-NEXT:    retq
  %1 = call i64 @llvm.vector.reduce.smin.v16i64(<16 x i64> %a0)
  ret i64 %1
}

;
; vXi32
;

define i32 @test_v2i32(<2 x i32> %a0) {
; SSE2-LABEL: test_v2i32:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movd %xmm0, %ecx
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[1,1,1,1]
; SSE2-NEXT:    movd %xmm0, %eax
; SSE2-NEXT:    cmpl %eax, %ecx
; SSE2-NEXT:    cmovll %ecx, %eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v2i32:
; SSE4:       # %bb.0:
; SSE4-NEXT:    pextrd $1, %xmm0, %eax
; SSE4-NEXT:    movd %xmm0, %ecx
; SSE4-NEXT:    cmpl %eax, %ecx
; SSE4-NEXT:    cmovll %ecx, %eax
; SSE4-NEXT:    retq
;
; AVX-LABEL: test_v2i32:
; AVX:       # %bb.0:
; AVX-NEXT:    vpextrd $1, %xmm0, %eax
; AVX-NEXT:    vmovd %xmm0, %ecx
; AVX-NEXT:    cmpl %eax, %ecx
; AVX-NEXT:    cmovll %ecx, %eax
; AVX-NEXT:    retq
;
; AVX512-LABEL: test_v2i32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpextrd $1, %xmm0, %eax
; AVX512-NEXT:    vmovd %xmm0, %ecx
; AVX512-NEXT:    cmpl %eax, %ecx
; AVX512-NEXT:    cmovll %ecx, %eax
; AVX512-NEXT:    retq
  %1 = call i32 @llvm.vector.reduce.smin.v2i32(<2 x i32> %a0)
  ret i32 %1
}

define i32 @test_v4i32(<4 x i32> %a0) {
; SSE2-LABEL: test_v4i32:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pshufd {{.*#+}} xmm1 = xmm0[3,3,3,3]
; SSE2-NEXT:    movd %xmm1, %ecx
; SSE2-NEXT:    pshufd {{.*#+}} xmm1 = xmm0[2,3,2,3]
; SSE2-NEXT:    movd %xmm1, %edx
; SSE2-NEXT:    movd %xmm0, %esi
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[1,1,1,1]
; SSE2-NEXT:    movd %xmm0, %eax
; SSE2-NEXT:    cmpl %eax, %esi
; SSE2-NEXT:    cmovll %esi, %eax
; SSE2-NEXT:    cmpl %edx, %eax
; SSE2-NEXT:    cmovgel %edx, %eax
; SSE2-NEXT:    cmpl %ecx, %eax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v4i32:
; SSE4:       # %bb.0:
; SSE4-NEXT:    pextrd $3, %xmm0, %ecx
; SSE4-NEXT:    pextrd $2, %xmm0, %edx
; SSE4-NEXT:    pextrd $1, %xmm0, %eax
; SSE4-NEXT:    movd %xmm0, %esi
; SSE4-NEXT:    cmpl %eax, %esi
; SSE4-NEXT:    cmovll %esi, %eax
; SSE4-NEXT:    cmpl %edx, %eax
; SSE4-NEXT:    cmovgel %edx, %eax
; SSE4-NEXT:    cmpl %ecx, %eax
; SSE4-NEXT:    cmovgel %ecx, %eax
; SSE4-NEXT:    retq
;
; AVX-LABEL: test_v4i32:
; AVX:       # %bb.0:
; AVX-NEXT:    vpextrd $3, %xmm0, %ecx
; AVX-NEXT:    vpextrd $2, %xmm0, %edx
; AVX-NEXT:    vpextrd $1, %xmm0, %eax
; AVX-NEXT:    vmovd %xmm0, %esi
; AVX-NEXT:    cmpl %eax, %esi
; AVX-NEXT:    cmovll %esi, %eax
; AVX-NEXT:    cmpl %edx, %eax
; AVX-NEXT:    cmovgel %edx, %eax
; AVX-NEXT:    cmpl %ecx, %eax
; AVX-NEXT:    cmovgel %ecx, %eax
; AVX-NEXT:    retq
;
; AVX512-LABEL: test_v4i32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpextrd $3, %xmm0, %ecx
; AVX512-NEXT:    vpextrd $2, %xmm0, %edx
; AVX512-NEXT:    vpextrd $1, %xmm0, %eax
; AVX512-NEXT:    vmovd %xmm0, %esi
; AVX512-NEXT:    cmpl %eax, %esi
; AVX512-NEXT:    cmovll %esi, %eax
; AVX512-NEXT:    cmpl %edx, %eax
; AVX512-NEXT:    cmovgel %edx, %eax
; AVX512-NEXT:    cmpl %ecx, %eax
; AVX512-NEXT:    cmovgel %ecx, %eax
; AVX512-NEXT:    retq
  %1 = call i32 @llvm.vector.reduce.smin.v4i32(<4 x i32> %a0)
  ret i32 %1
}

define i32 @test_v8i32(<8 x i32> %a0) {
; SSE2-LABEL: test_v8i32:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa %xmm1, %xmm2
; SSE2-NEXT:    pcmpgtd %xmm0, %xmm2
; SSE2-NEXT:    pand %xmm2, %xmm0
; SSE2-NEXT:    pandn %xmm1, %xmm2
; SSE2-NEXT:    por %xmm0, %xmm2
; SSE2-NEXT:    movd %xmm2, %ecx
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm2[1,1,1,1]
; SSE2-NEXT:    movd %xmm0, %eax
; SSE2-NEXT:    cmpl %eax, %ecx
; SSE2-NEXT:    cmovll %ecx, %eax
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm2[2,3,2,3]
; SSE2-NEXT:    movd %xmm0, %ecx
; SSE2-NEXT:    cmpl %ecx, %eax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm2[3,3,3,3]
; SSE2-NEXT:    movd %xmm0, %ecx
; SSE2-NEXT:    cmpl %ecx, %eax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v8i32:
; SSE4:       # %bb.0:
; SSE4-NEXT:    pminsd %xmm1, %xmm0
; SSE4-NEXT:    pextrd $1, %xmm0, %eax
; SSE4-NEXT:    movd %xmm0, %ecx
; SSE4-NEXT:    cmpl %eax, %ecx
; SSE4-NEXT:    cmovll %ecx, %eax
; SSE4-NEXT:    pextrd $2, %xmm0, %ecx
; SSE4-NEXT:    cmpl %ecx, %eax
; SSE4-NEXT:    cmovgel %ecx, %eax
; SSE4-NEXT:    pextrd $3, %xmm0, %ecx
; SSE4-NEXT:    cmpl %ecx, %eax
; SSE4-NEXT:    cmovgel %ecx, %eax
; SSE4-NEXT:    retq
;
; AVX1-LABEL: test_v8i32:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm1
; AVX1-NEXT:    vpminsd %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vpextrd $1, %xmm0, %eax
; AVX1-NEXT:    vmovd %xmm0, %ecx
; AVX1-NEXT:    cmpl %eax, %ecx
; AVX1-NEXT:    cmovll %ecx, %eax
; AVX1-NEXT:    vpextrd $2, %xmm0, %ecx
; AVX1-NEXT:    cmpl %ecx, %eax
; AVX1-NEXT:    cmovgel %ecx, %eax
; AVX1-NEXT:    vpextrd $3, %xmm0, %ecx
; AVX1-NEXT:    cmpl %ecx, %eax
; AVX1-NEXT:    cmovgel %ecx, %eax
; AVX1-NEXT:    vzeroupper
; AVX1-NEXT:    retq
;
; AVX2-LABEL: test_v8i32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpminsd %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vpextrd $1, %xmm0, %eax
; AVX2-NEXT:    vmovd %xmm0, %ecx
; AVX2-NEXT:    cmpl %eax, %ecx
; AVX2-NEXT:    cmovll %ecx, %eax
; AVX2-NEXT:    vpextrd $2, %xmm0, %ecx
; AVX2-NEXT:    cmpl %ecx, %eax
; AVX2-NEXT:    cmovgel %ecx, %eax
; AVX2-NEXT:    vpextrd $3, %xmm0, %ecx
; AVX2-NEXT:    cmpl %ecx, %eax
; AVX2-NEXT:    cmovgel %ecx, %eax
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_v8i32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512-NEXT:    vpminsd %xmm1, %xmm0, %xmm0
; AVX512-NEXT:    vpextrd $1, %xmm0, %eax
; AVX512-NEXT:    vmovd %xmm0, %ecx
; AVX512-NEXT:    cmpl %eax, %ecx
; AVX512-NEXT:    cmovll %ecx, %eax
; AVX512-NEXT:    vpextrd $2, %xmm0, %ecx
; AVX512-NEXT:    cmpl %ecx, %eax
; AVX512-NEXT:    cmovgel %ecx, %eax
; AVX512-NEXT:    vpextrd $3, %xmm0, %ecx
; AVX512-NEXT:    cmpl %ecx, %eax
; AVX512-NEXT:    cmovgel %ecx, %eax
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %1 = call i32 @llvm.vector.reduce.smin.v8i32(<8 x i32> %a0)
  ret i32 %1
}

define i32 @test_v16i32(<16 x i32> %a0) {
; SSE2-LABEL: test_v16i32:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa %xmm2, %xmm4
; SSE2-NEXT:    pcmpgtd %xmm0, %xmm4
; SSE2-NEXT:    pand %xmm4, %xmm0
; SSE2-NEXT:    pandn %xmm2, %xmm4
; SSE2-NEXT:    por %xmm0, %xmm4
; SSE2-NEXT:    movdqa %xmm3, %xmm0
; SSE2-NEXT:    pcmpgtd %xmm1, %xmm0
; SSE2-NEXT:    pand %xmm0, %xmm1
; SSE2-NEXT:    pandn %xmm3, %xmm0
; SSE2-NEXT:    por %xmm1, %xmm0
; SSE2-NEXT:    movdqa %xmm0, %xmm1
; SSE2-NEXT:    pcmpgtd %xmm4, %xmm1
; SSE2-NEXT:    pand %xmm1, %xmm4
; SSE2-NEXT:    pandn %xmm0, %xmm1
; SSE2-NEXT:    por %xmm4, %xmm1
; SSE2-NEXT:    movd %xmm1, %ecx
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm1[1,1,1,1]
; SSE2-NEXT:    movd %xmm0, %eax
; SSE2-NEXT:    cmpl %eax, %ecx
; SSE2-NEXT:    cmovll %ecx, %eax
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm1[2,3,2,3]
; SSE2-NEXT:    movd %xmm0, %ecx
; SSE2-NEXT:    cmpl %ecx, %eax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm1[3,3,3,3]
; SSE2-NEXT:    movd %xmm0, %ecx
; SSE2-NEXT:    cmpl %ecx, %eax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v16i32:
; SSE4:       # %bb.0:
; SSE4-NEXT:    pminsd %xmm3, %xmm1
; SSE4-NEXT:    pminsd %xmm2, %xmm0
; SSE4-NEXT:    pminsd %xmm1, %xmm0
; SSE4-NEXT:    pextrd $1, %xmm0, %eax
; SSE4-NEXT:    movd %xmm0, %ecx
; SSE4-NEXT:    cmpl %eax, %ecx
; SSE4-NEXT:    cmovll %ecx, %eax
; SSE4-NEXT:    pextrd $2, %xmm0, %ecx
; SSE4-NEXT:    cmpl %ecx, %eax
; SSE4-NEXT:    cmovgel %ecx, %eax
; SSE4-NEXT:    pextrd $3, %xmm0, %ecx
; SSE4-NEXT:    cmpl %ecx, %eax
; SSE4-NEXT:    cmovgel %ecx, %eax
; SSE4-NEXT:    retq
;
; AVX1-LABEL: test_v16i32:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm3
; AVX1-NEXT:    vpminsd %xmm2, %xmm3, %xmm2
; AVX1-NEXT:    vpminsd %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vpminsd %xmm2, %xmm0, %xmm0
; AVX1-NEXT:    vpextrd $1, %xmm0, %eax
; AVX1-NEXT:    vmovd %xmm0, %ecx
; AVX1-NEXT:    cmpl %eax, %ecx
; AVX1-NEXT:    cmovll %ecx, %eax
; AVX1-NEXT:    vpextrd $2, %xmm0, %ecx
; AVX1-NEXT:    cmpl %ecx, %eax
; AVX1-NEXT:    cmovgel %ecx, %eax
; AVX1-NEXT:    vpextrd $3, %xmm0, %ecx
; AVX1-NEXT:    cmpl %ecx, %eax
; AVX1-NEXT:    cmovgel %ecx, %eax
; AVX1-NEXT:    vzeroupper
; AVX1-NEXT:    retq
;
; AVX2-LABEL: test_v16i32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpminsd %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpminsd %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vpextrd $1, %xmm0, %eax
; AVX2-NEXT:    vmovd %xmm0, %ecx
; AVX2-NEXT:    cmpl %eax, %ecx
; AVX2-NEXT:    cmovll %ecx, %eax
; AVX2-NEXT:    vpextrd $2, %xmm0, %ecx
; AVX2-NEXT:    cmpl %ecx, %eax
; AVX2-NEXT:    cmovgel %ecx, %eax
; AVX2-NEXT:    vpextrd $3, %xmm0, %ecx
; AVX2-NEXT:    cmpl %ecx, %eax
; AVX2-NEXT:    cmovgel %ecx, %eax
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_v16i32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vextracti64x4 $1, %zmm0, %ymm1
; AVX512-NEXT:    vpminsd %ymm1, %ymm0, %ymm0
; AVX512-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512-NEXT:    vpminsd %xmm1, %xmm0, %xmm0
; AVX512-NEXT:    vpextrd $1, %xmm0, %eax
; AVX512-NEXT:    vmovd %xmm0, %ecx
; AVX512-NEXT:    cmpl %eax, %ecx
; AVX512-NEXT:    cmovll %ecx, %eax
; AVX512-NEXT:    vpextrd $2, %xmm0, %ecx
; AVX512-NEXT:    cmpl %ecx, %eax
; AVX512-NEXT:    cmovgel %ecx, %eax
; AVX512-NEXT:    vpextrd $3, %xmm0, %ecx
; AVX512-NEXT:    cmpl %ecx, %eax
; AVX512-NEXT:    cmovgel %ecx, %eax
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %1 = call i32 @llvm.vector.reduce.smin.v16i32(<16 x i32> %a0)
  ret i32 %1
}

define i32 @test_v32i32(<32 x i32> %a0) {
; SSE2-LABEL: test_v32i32:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa %xmm4, %xmm8
; SSE2-NEXT:    pcmpgtd %xmm0, %xmm8
; SSE2-NEXT:    pand %xmm8, %xmm0
; SSE2-NEXT:    pandn %xmm4, %xmm8
; SSE2-NEXT:    por %xmm0, %xmm8
; SSE2-NEXT:    movdqa %xmm6, %xmm4
; SSE2-NEXT:    pcmpgtd %xmm2, %xmm4
; SSE2-NEXT:    pand %xmm4, %xmm2
; SSE2-NEXT:    pandn %xmm6, %xmm4
; SSE2-NEXT:    por %xmm2, %xmm4
; SSE2-NEXT:    movdqa %xmm4, %xmm0
; SSE2-NEXT:    pcmpgtd %xmm8, %xmm0
; SSE2-NEXT:    pand %xmm0, %xmm8
; SSE2-NEXT:    pandn %xmm4, %xmm0
; SSE2-NEXT:    por %xmm8, %xmm0
; SSE2-NEXT:    movdqa %xmm5, %xmm2
; SSE2-NEXT:    pcmpgtd %xmm1, %xmm2
; SSE2-NEXT:    pand %xmm2, %xmm1
; SSE2-NEXT:    pandn %xmm5, %xmm2
; SSE2-NEXT:    por %xmm1, %xmm2
; SSE2-NEXT:    movdqa %xmm7, %xmm1
; SSE2-NEXT:    pcmpgtd %xmm3, %xmm1
; SSE2-NEXT:    pand %xmm1, %xmm3
; SSE2-NEXT:    pandn %xmm7, %xmm1
; SSE2-NEXT:    por %xmm3, %xmm1
; SSE2-NEXT:    movdqa %xmm1, %xmm3
; SSE2-NEXT:    pcmpgtd %xmm2, %xmm3
; SSE2-NEXT:    pand %xmm3, %xmm2
; SSE2-NEXT:    pandn %xmm1, %xmm3
; SSE2-NEXT:    por %xmm2, %xmm3
; SSE2-NEXT:    movdqa %xmm3, %xmm1
; SSE2-NEXT:    pcmpgtd %xmm0, %xmm1
; SSE2-NEXT:    pand %xmm1, %xmm0
; SSE2-NEXT:    pandn %xmm3, %xmm1
; SSE2-NEXT:    por %xmm0, %xmm1
; SSE2-NEXT:    movd %xmm1, %ecx
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm1[1,1,1,1]
; SSE2-NEXT:    movd %xmm0, %eax
; SSE2-NEXT:    cmpl %eax, %ecx
; SSE2-NEXT:    cmovll %ecx, %eax
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm1[2,3,2,3]
; SSE2-NEXT:    movd %xmm0, %ecx
; SSE2-NEXT:    cmpl %ecx, %eax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm1[3,3,3,3]
; SSE2-NEXT:    movd %xmm0, %ecx
; SSE2-NEXT:    cmpl %ecx, %eax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v32i32:
; SSE4:       # %bb.0:
; SSE4-NEXT:    pminsd %xmm7, %xmm3
; SSE4-NEXT:    pminsd %xmm5, %xmm1
; SSE4-NEXT:    pminsd %xmm3, %xmm1
; SSE4-NEXT:    pminsd %xmm6, %xmm2
; SSE4-NEXT:    pminsd %xmm4, %xmm0
; SSE4-NEXT:    pminsd %xmm2, %xmm0
; SSE4-NEXT:    pminsd %xmm1, %xmm0
; SSE4-NEXT:    pextrd $1, %xmm0, %eax
; SSE4-NEXT:    movd %xmm0, %ecx
; SSE4-NEXT:    cmpl %eax, %ecx
; SSE4-NEXT:    cmovll %ecx, %eax
; SSE4-NEXT:    pextrd $2, %xmm0, %ecx
; SSE4-NEXT:    cmpl %ecx, %eax
; SSE4-NEXT:    cmovgel %ecx, %eax
; SSE4-NEXT:    pextrd $3, %xmm0, %ecx
; SSE4-NEXT:    cmpl %ecx, %eax
; SSE4-NEXT:    cmovgel %ecx, %eax
; SSE4-NEXT:    retq
;
; AVX1-LABEL: test_v32i32:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm3, %xmm4
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm5
; AVX1-NEXT:    vpminsd %xmm4, %xmm5, %xmm4
; AVX1-NEXT:    vextractf128 $1, %ymm2, %xmm5
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm6
; AVX1-NEXT:    vpminsd %xmm5, %xmm6, %xmm5
; AVX1-NEXT:    vpminsd %xmm4, %xmm5, %xmm4
; AVX1-NEXT:    vpminsd %xmm3, %xmm1, %xmm1
; AVX1-NEXT:    vpminsd %xmm2, %xmm0, %xmm0
; AVX1-NEXT:    vpminsd %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vpminsd %xmm4, %xmm0, %xmm0
; AVX1-NEXT:    vpextrd $1, %xmm0, %eax
; AVX1-NEXT:    vmovd %xmm0, %ecx
; AVX1-NEXT:    cmpl %eax, %ecx
; AVX1-NEXT:    cmovll %ecx, %eax
; AVX1-NEXT:    vpextrd $2, %xmm0, %ecx
; AVX1-NEXT:    cmpl %ecx, %eax
; AVX1-NEXT:    cmovgel %ecx, %eax
; AVX1-NEXT:    vpextrd $3, %xmm0, %ecx
; AVX1-NEXT:    cmpl %ecx, %eax
; AVX1-NEXT:    cmovgel %ecx, %eax
; AVX1-NEXT:    vzeroupper
; AVX1-NEXT:    retq
;
; AVX2-LABEL: test_v32i32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpminsd %ymm3, %ymm1, %ymm1
; AVX2-NEXT:    vpminsd %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpminsd %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpminsd %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vpextrd $1, %xmm0, %eax
; AVX2-NEXT:    vmovd %xmm0, %ecx
; AVX2-NEXT:    cmpl %eax, %ecx
; AVX2-NEXT:    cmovll %ecx, %eax
; AVX2-NEXT:    vpextrd $2, %xmm0, %ecx
; AVX2-NEXT:    cmpl %ecx, %eax
; AVX2-NEXT:    cmovgel %ecx, %eax
; AVX2-NEXT:    vpextrd $3, %xmm0, %ecx
; AVX2-NEXT:    cmpl %ecx, %eax
; AVX2-NEXT:    cmovgel %ecx, %eax
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_v32i32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpminsd %zmm1, %zmm0, %zmm0
; AVX512-NEXT:    vextracti64x4 $1, %zmm0, %ymm1
; AVX512-NEXT:    vpminsd %ymm1, %ymm0, %ymm0
; AVX512-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512-NEXT:    vpminsd %xmm1, %xmm0, %xmm0
; AVX512-NEXT:    vpextrd $1, %xmm0, %eax
; AVX512-NEXT:    vmovd %xmm0, %ecx
; AVX512-NEXT:    cmpl %eax, %ecx
; AVX512-NEXT:    cmovll %ecx, %eax
; AVX512-NEXT:    vpextrd $2, %xmm0, %ecx
; AVX512-NEXT:    cmpl %ecx, %eax
; AVX512-NEXT:    cmovgel %ecx, %eax
; AVX512-NEXT:    vpextrd $3, %xmm0, %ecx
; AVX512-NEXT:    cmpl %ecx, %eax
; AVX512-NEXT:    cmovgel %ecx, %eax
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %1 = call i32 @llvm.vector.reduce.smin.v32i32(<32 x i32> %a0)
  ret i32 %1
}

;
; vXi16
;

define i16 @test_v2i16(<2 x i16> %a0) {
; SSE2-LABEL: test_v2i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pextrw $1, %xmm0, %eax
; SSE2-NEXT:    movd %xmm0, %ecx
; SSE2-NEXT:    cmpw %ax, %cx
; SSE2-NEXT:    cmovll %ecx, %eax
; SSE2-NEXT:    # kill: def $ax killed $ax killed $eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v2i16:
; SSE4:       # %bb.0:
; SSE4-NEXT:    movl $32767, %eax # imm = 0x7FFF
; SSE4-NEXT:    pinsrw $2, %eax, %xmm0
; SSE4-NEXT:    pinsrw $3, %eax, %xmm0
; SSE4-NEXT:    pinsrw $4, %eax, %xmm0
; SSE4-NEXT:    pinsrw $5, %eax, %xmm0
; SSE4-NEXT:    pinsrw $6, %eax, %xmm0
; SSE4-NEXT:    pinsrw $7, %eax, %xmm0
; SSE4-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; SSE4-NEXT:    phminposuw %xmm0, %xmm0
; SSE4-NEXT:    movd %xmm0, %eax
; SSE4-NEXT:    xorl $32768, %eax # imm = 0x8000
; SSE4-NEXT:    # kill: def $ax killed $ax killed $eax
; SSE4-NEXT:    retq
;
; AVX-LABEL: test_v2i16:
; AVX:       # %bb.0:
; AVX-NEXT:    movl $32767, %eax # imm = 0x7FFF
; AVX-NEXT:    vpinsrw $2, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrw $3, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrw $4, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrw $5, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrw $6, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrw $7, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX-NEXT:    vphminposuw %xmm0, %xmm0
; AVX-NEXT:    vmovd %xmm0, %eax
; AVX-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX-NEXT:    retq
;
; AVX512BW-LABEL: test_v2i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    movl $32767, %eax # imm = 0x7FFF
; AVX512BW-NEXT:    vpinsrw $2, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrw $3, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrw $4, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrw $5, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrw $6, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrw $7, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX512BW-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512BW-NEXT:    vmovd %xmm0, %eax
; AVX512BW-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX512BW-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v2i16:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    movl $32767, %eax # imm = 0x7FFF
; AVX512VL-NEXT:    vpinsrw $2, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrw $3, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrw $4, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrw $5, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrw $6, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrw $7, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpxord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %xmm0, %xmm0
; AVX512VL-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512VL-NEXT:    vmovd %xmm0, %eax
; AVX512VL-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX512VL-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX512VL-NEXT:    retq
  %1 = call i16 @llvm.vector.reduce.smin.v2i16(<2 x i16> %a0)
  ret i16 %1
}

define i16 @test_v4i16(<4 x i16> %a0) {
; SSE2-LABEL: test_v4i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pextrw $1, %xmm0, %eax
; SSE2-NEXT:    movd %xmm0, %ecx
; SSE2-NEXT:    cmpw %ax, %cx
; SSE2-NEXT:    cmovll %ecx, %eax
; SSE2-NEXT:    pextrw $2, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $3, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    # kill: def $ax killed $ax killed $eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v4i16:
; SSE4:       # %bb.0:
; SSE4-NEXT:    movl $32767, %eax # imm = 0x7FFF
; SSE4-NEXT:    pinsrw $4, %eax, %xmm0
; SSE4-NEXT:    pinsrw $5, %eax, %xmm0
; SSE4-NEXT:    pinsrw $6, %eax, %xmm0
; SSE4-NEXT:    pinsrw $7, %eax, %xmm0
; SSE4-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; SSE4-NEXT:    phminposuw %xmm0, %xmm0
; SSE4-NEXT:    movd %xmm0, %eax
; SSE4-NEXT:    xorl $32768, %eax # imm = 0x8000
; SSE4-NEXT:    # kill: def $ax killed $ax killed $eax
; SSE4-NEXT:    retq
;
; AVX-LABEL: test_v4i16:
; AVX:       # %bb.0:
; AVX-NEXT:    movl $32767, %eax # imm = 0x7FFF
; AVX-NEXT:    vpinsrw $4, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrw $5, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrw $6, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrw $7, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX-NEXT:    vphminposuw %xmm0, %xmm0
; AVX-NEXT:    vmovd %xmm0, %eax
; AVX-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX-NEXT:    retq
;
; AVX512BW-LABEL: test_v4i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    movl $32767, %eax # imm = 0x7FFF
; AVX512BW-NEXT:    vpinsrw $4, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrw $5, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrw $6, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrw $7, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX512BW-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512BW-NEXT:    vmovd %xmm0, %eax
; AVX512BW-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX512BW-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v4i16:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    movl $32767, %eax # imm = 0x7FFF
; AVX512VL-NEXT:    vpinsrw $4, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrw $5, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrw $6, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrw $7, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpxord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %xmm0, %xmm0
; AVX512VL-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512VL-NEXT:    vmovd %xmm0, %eax
; AVX512VL-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX512VL-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX512VL-NEXT:    retq
  %1 = call i16 @llvm.vector.reduce.smin.v4i16(<4 x i16> %a0)
  ret i16 %1
}

define i16 @test_v8i16(<8 x i16> %a0) {
; SSE2-LABEL: test_v8i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pextrw $7, %xmm0, %ecx
; SSE2-NEXT:    pextrw $6, %xmm0, %edx
; SSE2-NEXT:    pextrw $5, %xmm0, %esi
; SSE2-NEXT:    pextrw $4, %xmm0, %edi
; SSE2-NEXT:    pextrw $3, %xmm0, %r8d
; SSE2-NEXT:    pextrw $2, %xmm0, %r9d
; SSE2-NEXT:    pextrw $1, %xmm0, %eax
; SSE2-NEXT:    movd %xmm0, %r10d
; SSE2-NEXT:    cmpw %ax, %r10w
; SSE2-NEXT:    cmovll %r10d, %eax
; SSE2-NEXT:    cmpw %r9w, %ax
; SSE2-NEXT:    cmovgel %r9d, %eax
; SSE2-NEXT:    cmpw %r8w, %ax
; SSE2-NEXT:    cmovgel %r8d, %eax
; SSE2-NEXT:    cmpw %di, %ax
; SSE2-NEXT:    cmovgel %edi, %eax
; SSE2-NEXT:    cmpw %si, %ax
; SSE2-NEXT:    cmovgel %esi, %eax
; SSE2-NEXT:    cmpw %dx, %ax
; SSE2-NEXT:    cmovgel %edx, %eax
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    # kill: def $ax killed $ax killed $eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v8i16:
; SSE4:       # %bb.0:
; SSE4-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; SSE4-NEXT:    phminposuw %xmm0, %xmm0
; SSE4-NEXT:    movd %xmm0, %eax
; SSE4-NEXT:    xorl $32768, %eax # imm = 0x8000
; SSE4-NEXT:    # kill: def $ax killed $ax killed $eax
; SSE4-NEXT:    retq
;
; AVX-LABEL: test_v8i16:
; AVX:       # %bb.0:
; AVX-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX-NEXT:    vphminposuw %xmm0, %xmm0
; AVX-NEXT:    vmovd %xmm0, %eax
; AVX-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX-NEXT:    retq
;
; AVX512BW-LABEL: test_v8i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX512BW-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512BW-NEXT:    vmovd %xmm0, %eax
; AVX512BW-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX512BW-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v8i16:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    vpxord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %xmm0, %xmm0
; AVX512VL-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512VL-NEXT:    vmovd %xmm0, %eax
; AVX512VL-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX512VL-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX512VL-NEXT:    retq
  %1 = call i16 @llvm.vector.reduce.smin.v8i16(<8 x i16> %a0)
  ret i16 %1
}

define i16 @test_v16i16(<16 x i16> %a0) {
; SSE2-LABEL: test_v16i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pminsw %xmm1, %xmm0
; SSE2-NEXT:    pextrw $1, %xmm0, %eax
; SSE2-NEXT:    movd %xmm0, %ecx
; SSE2-NEXT:    cmpw %ax, %cx
; SSE2-NEXT:    cmovll %ecx, %eax
; SSE2-NEXT:    pextrw $2, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $3, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $4, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $5, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $6, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $7, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    # kill: def $ax killed $ax killed $eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v16i16:
; SSE4:       # %bb.0:
; SSE4-NEXT:    pminsw %xmm1, %xmm0
; SSE4-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; SSE4-NEXT:    phminposuw %xmm0, %xmm0
; SSE4-NEXT:    movd %xmm0, %eax
; SSE4-NEXT:    xorl $32768, %eax # imm = 0x8000
; SSE4-NEXT:    # kill: def $ax killed $ax killed $eax
; SSE4-NEXT:    retq
;
; AVX1-LABEL: test_v16i16:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm1
; AVX1-NEXT:    vpminsw %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX1-NEXT:    vphminposuw %xmm0, %xmm0
; AVX1-NEXT:    vmovd %xmm0, %eax
; AVX1-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX1-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX1-NEXT:    vzeroupper
; AVX1-NEXT:    retq
;
; AVX2-LABEL: test_v16i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpminsw %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX2-NEXT:    vphminposuw %xmm0, %xmm0
; AVX2-NEXT:    vmovd %xmm0, %eax
; AVX2-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX2-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512BW-LABEL: test_v16i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512BW-NEXT:    vpminsw %xmm1, %xmm0, %xmm0
; AVX512BW-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX512BW-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512BW-NEXT:    vmovd %xmm0, %eax
; AVX512BW-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX512BW-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v16i16:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512VL-NEXT:    vpminsw %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vpxord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %xmm0, %xmm0
; AVX512VL-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512VL-NEXT:    vmovd %xmm0, %eax
; AVX512VL-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX512VL-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX512VL-NEXT:    vzeroupper
; AVX512VL-NEXT:    retq
  %1 = call i16 @llvm.vector.reduce.smin.v16i16(<16 x i16> %a0)
  ret i16 %1
}

define i16 @test_v32i16(<32 x i16> %a0) {
; SSE2-LABEL: test_v32i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pminsw %xmm3, %xmm1
; SSE2-NEXT:    pminsw %xmm2, %xmm0
; SSE2-NEXT:    pminsw %xmm1, %xmm0
; SSE2-NEXT:    pextrw $1, %xmm0, %eax
; SSE2-NEXT:    movd %xmm0, %ecx
; SSE2-NEXT:    cmpw %ax, %cx
; SSE2-NEXT:    cmovll %ecx, %eax
; SSE2-NEXT:    pextrw $2, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $3, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $4, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $5, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $6, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $7, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    # kill: def $ax killed $ax killed $eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v32i16:
; SSE4:       # %bb.0:
; SSE4-NEXT:    pminsw %xmm3, %xmm1
; SSE4-NEXT:    pminsw %xmm2, %xmm0
; SSE4-NEXT:    pminsw %xmm1, %xmm0
; SSE4-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; SSE4-NEXT:    phminposuw %xmm0, %xmm0
; SSE4-NEXT:    movd %xmm0, %eax
; SSE4-NEXT:    xorl $32768, %eax # imm = 0x8000
; SSE4-NEXT:    # kill: def $ax killed $ax killed $eax
; SSE4-NEXT:    retq
;
; AVX1-LABEL: test_v32i16:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm3
; AVX1-NEXT:    vpminsw %xmm2, %xmm3, %xmm2
; AVX1-NEXT:    vpminsw %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vpminsw %xmm2, %xmm0, %xmm0
; AVX1-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX1-NEXT:    vphminposuw %xmm0, %xmm0
; AVX1-NEXT:    vmovd %xmm0, %eax
; AVX1-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX1-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX1-NEXT:    vzeroupper
; AVX1-NEXT:    retq
;
; AVX2-LABEL: test_v32i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpminsw %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpminsw %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX2-NEXT:    vphminposuw %xmm0, %xmm0
; AVX2-NEXT:    vmovd %xmm0, %eax
; AVX2-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX2-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512BW-LABEL: test_v32i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vextracti64x4 $1, %zmm0, %ymm1
; AVX512BW-NEXT:    vpminsw %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512BW-NEXT:    vpminsw %xmm1, %xmm0, %xmm0
; AVX512BW-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX512BW-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512BW-NEXT:    vmovd %xmm0, %eax
; AVX512BW-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX512BW-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v32i16:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    vextracti64x4 $1, %zmm0, %ymm1
; AVX512VL-NEXT:    vpminsw %ymm1, %ymm0, %ymm0
; AVX512VL-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512VL-NEXT:    vpminsw %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vpxord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %xmm0, %xmm0
; AVX512VL-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512VL-NEXT:    vmovd %xmm0, %eax
; AVX512VL-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX512VL-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX512VL-NEXT:    vzeroupper
; AVX512VL-NEXT:    retq
  %1 = call i16 @llvm.vector.reduce.smin.v32i16(<32 x i16> %a0)
  ret i16 %1
}

define i16 @test_v64i16(<64 x i16> %a0) {
; SSE2-LABEL: test_v64i16:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pminsw %xmm7, %xmm3
; SSE2-NEXT:    pminsw %xmm5, %xmm1
; SSE2-NEXT:    pminsw %xmm3, %xmm1
; SSE2-NEXT:    pminsw %xmm6, %xmm2
; SSE2-NEXT:    pminsw %xmm4, %xmm0
; SSE2-NEXT:    pminsw %xmm2, %xmm0
; SSE2-NEXT:    pminsw %xmm1, %xmm0
; SSE2-NEXT:    pextrw $1, %xmm0, %eax
; SSE2-NEXT:    movd %xmm0, %ecx
; SSE2-NEXT:    cmpw %ax, %cx
; SSE2-NEXT:    cmovll %ecx, %eax
; SSE2-NEXT:    pextrw $2, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $3, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $4, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $5, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $6, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    pextrw $7, %xmm0, %ecx
; SSE2-NEXT:    cmpw %cx, %ax
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    # kill: def $ax killed $ax killed $eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v64i16:
; SSE4:       # %bb.0:
; SSE4-NEXT:    pminsw %xmm7, %xmm3
; SSE4-NEXT:    pminsw %xmm5, %xmm1
; SSE4-NEXT:    pminsw %xmm3, %xmm1
; SSE4-NEXT:    pminsw %xmm6, %xmm2
; SSE4-NEXT:    pminsw %xmm4, %xmm0
; SSE4-NEXT:    pminsw %xmm2, %xmm0
; SSE4-NEXT:    pminsw %xmm1, %xmm0
; SSE4-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; SSE4-NEXT:    phminposuw %xmm0, %xmm0
; SSE4-NEXT:    movd %xmm0, %eax
; SSE4-NEXT:    xorl $32768, %eax # imm = 0x8000
; SSE4-NEXT:    # kill: def $ax killed $ax killed $eax
; SSE4-NEXT:    retq
;
; AVX1-LABEL: test_v64i16:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm3, %xmm4
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm5
; AVX1-NEXT:    vpminsw %xmm4, %xmm5, %xmm4
; AVX1-NEXT:    vextractf128 $1, %ymm2, %xmm5
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm6
; AVX1-NEXT:    vpminsw %xmm5, %xmm6, %xmm5
; AVX1-NEXT:    vpminsw %xmm4, %xmm5, %xmm4
; AVX1-NEXT:    vpminsw %xmm3, %xmm1, %xmm1
; AVX1-NEXT:    vpminsw %xmm2, %xmm0, %xmm0
; AVX1-NEXT:    vpminsw %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vpminsw %xmm4, %xmm0, %xmm0
; AVX1-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX1-NEXT:    vphminposuw %xmm0, %xmm0
; AVX1-NEXT:    vmovd %xmm0, %eax
; AVX1-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX1-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX1-NEXT:    vzeroupper
; AVX1-NEXT:    retq
;
; AVX2-LABEL: test_v64i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpminsw %ymm3, %ymm1, %ymm1
; AVX2-NEXT:    vpminsw %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpminsw %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpminsw %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX2-NEXT:    vphminposuw %xmm0, %xmm0
; AVX2-NEXT:    vmovd %xmm0, %eax
; AVX2-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX2-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512BW-LABEL: test_v64i16:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vpminsw %zmm1, %zmm0, %zmm0
; AVX512BW-NEXT:    vextracti64x4 $1, %zmm0, %ymm1
; AVX512BW-NEXT:    vpminsw %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512BW-NEXT:    vpminsw %xmm1, %xmm0, %xmm0
; AVX512BW-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX512BW-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512BW-NEXT:    vmovd %xmm0, %eax
; AVX512BW-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX512BW-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v64i16:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    vpminsw %zmm1, %zmm0, %zmm0
; AVX512VL-NEXT:    vextracti64x4 $1, %zmm0, %ymm1
; AVX512VL-NEXT:    vpminsw %ymm1, %ymm0, %ymm0
; AVX512VL-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512VL-NEXT:    vpminsw %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vpxord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %xmm0, %xmm0
; AVX512VL-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512VL-NEXT:    vmovd %xmm0, %eax
; AVX512VL-NEXT:    xorl $32768, %eax # imm = 0x8000
; AVX512VL-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX512VL-NEXT:    vzeroupper
; AVX512VL-NEXT:    retq
  %1 = call i16 @llvm.vector.reduce.smin.v64i16(<64 x i16> %a0)
  ret i16 %1
}

;
; vXi8
;

define i8 @test_v2i8(<2 x i8> %a0) {
; SSE2-LABEL: test_v2i8:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movd %xmm0, %ecx
; SSE2-NEXT:    movl %ecx, %eax
; SSE2-NEXT:    shrl $8, %eax
; SSE2-NEXT:    cmpb %al, %cl
; SSE2-NEXT:    cmovll %ecx, %eax
; SSE2-NEXT:    # kill: def $al killed $al killed $eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v2i8:
; SSE4:       # %bb.0:
; SSE4-NEXT:    movl $127, %eax
; SSE4-NEXT:    pinsrb $2, %eax, %xmm0
; SSE4-NEXT:    pinsrb $3, %eax, %xmm0
; SSE4-NEXT:    pinsrb $4, %eax, %xmm0
; SSE4-NEXT:    pinsrb $5, %eax, %xmm0
; SSE4-NEXT:    pinsrb $6, %eax, %xmm0
; SSE4-NEXT:    pinsrb $7, %eax, %xmm0
; SSE4-NEXT:    pinsrb $8, %eax, %xmm0
; SSE4-NEXT:    pinsrb $9, %eax, %xmm0
; SSE4-NEXT:    pinsrb $10, %eax, %xmm0
; SSE4-NEXT:    pinsrb $11, %eax, %xmm0
; SSE4-NEXT:    pinsrb $12, %eax, %xmm0
; SSE4-NEXT:    pinsrb $13, %eax, %xmm0
; SSE4-NEXT:    pinsrb $14, %eax, %xmm0
; SSE4-NEXT:    pinsrb $15, %eax, %xmm0
; SSE4-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; SSE4-NEXT:    movdqa %xmm0, %xmm1
; SSE4-NEXT:    psrlw $8, %xmm1
; SSE4-NEXT:    pminub %xmm0, %xmm1
; SSE4-NEXT:    phminposuw %xmm1, %xmm0
; SSE4-NEXT:    movd %xmm0, %eax
; SSE4-NEXT:    addb $-128, %al
; SSE4-NEXT:    # kill: def $al killed $al killed $eax
; SSE4-NEXT:    retq
;
; AVX-LABEL: test_v2i8:
; AVX:       # %bb.0:
; AVX-NEXT:    movl $127, %eax
; AVX-NEXT:    vpinsrb $2, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $3, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $4, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $5, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $6, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $7, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $8, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $9, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $10, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $11, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $12, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $13, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $14, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $15, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX-NEXT:    vphminposuw %xmm0, %xmm0
; AVX-NEXT:    vmovd %xmm0, %eax
; AVX-NEXT:    addb $-128, %al
; AVX-NEXT:    # kill: def $al killed $al killed $eax
; AVX-NEXT:    retq
;
; AVX512BW-LABEL: test_v2i8:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    movl $127, %eax
; AVX512BW-NEXT:    vpinsrb $2, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $3, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $4, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $5, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $6, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $7, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $8, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $9, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $10, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $11, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $12, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $13, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $14, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $15, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX512BW-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX512BW-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX512BW-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512BW-NEXT:    vmovd %xmm0, %eax
; AVX512BW-NEXT:    addb $-128, %al
; AVX512BW-NEXT:    # kill: def $al killed $al killed $eax
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v2i8:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    movl $127, %eax
; AVX512VL-NEXT:    vpinsrb $2, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $3, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $4, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $5, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $6, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $7, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $8, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $9, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $10, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $11, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $12, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $13, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $14, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $15, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpxord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %xmm0, %xmm0
; AVX512VL-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX512VL-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512VL-NEXT:    vmovd %xmm0, %eax
; AVX512VL-NEXT:    addb $-128, %al
; AVX512VL-NEXT:    # kill: def $al killed $al killed $eax
; AVX512VL-NEXT:    retq
  %1 = call i8 @llvm.vector.reduce.smin.v2i8(<2 x i8> %a0)
  ret i8 %1
}

define i8 @test_v4i8(<4 x i8> %a0) {
; SSE2-LABEL: test_v4i8:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movd %xmm0, %eax
; SSE2-NEXT:    movl %eax, %ecx
; SSE2-NEXT:    shrl $8, %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovll %eax, %ecx
; SSE2-NEXT:    movl %eax, %edx
; SSE2-NEXT:    shrl $16, %edx
; SSE2-NEXT:    cmpb %dl, %cl
; SSE2-NEXT:    cmovll %ecx, %edx
; SSE2-NEXT:    shrl $24, %eax
; SSE2-NEXT:    cmpb %al, %dl
; SSE2-NEXT:    cmovll %edx, %eax
; SSE2-NEXT:    # kill: def $al killed $al killed $eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v4i8:
; SSE4:       # %bb.0:
; SSE4-NEXT:    movl $127, %eax
; SSE4-NEXT:    pinsrb $4, %eax, %xmm0
; SSE4-NEXT:    pinsrb $5, %eax, %xmm0
; SSE4-NEXT:    pinsrb $6, %eax, %xmm0
; SSE4-NEXT:    pinsrb $7, %eax, %xmm0
; SSE4-NEXT:    pinsrb $8, %eax, %xmm0
; SSE4-NEXT:    pinsrb $9, %eax, %xmm0
; SSE4-NEXT:    pinsrb $10, %eax, %xmm0
; SSE4-NEXT:    pinsrb $11, %eax, %xmm0
; SSE4-NEXT:    pinsrb $12, %eax, %xmm0
; SSE4-NEXT:    pinsrb $13, %eax, %xmm0
; SSE4-NEXT:    pinsrb $14, %eax, %xmm0
; SSE4-NEXT:    pinsrb $15, %eax, %xmm0
; SSE4-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; SSE4-NEXT:    movdqa %xmm0, %xmm1
; SSE4-NEXT:    psrlw $8, %xmm1
; SSE4-NEXT:    pminub %xmm0, %xmm1
; SSE4-NEXT:    phminposuw %xmm1, %xmm0
; SSE4-NEXT:    movd %xmm0, %eax
; SSE4-NEXT:    addb $-128, %al
; SSE4-NEXT:    # kill: def $al killed $al killed $eax
; SSE4-NEXT:    retq
;
; AVX-LABEL: test_v4i8:
; AVX:       # %bb.0:
; AVX-NEXT:    movl $127, %eax
; AVX-NEXT:    vpinsrb $4, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $5, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $6, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $7, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $8, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $9, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $10, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $11, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $12, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $13, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $14, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $15, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX-NEXT:    vphminposuw %xmm0, %xmm0
; AVX-NEXT:    vmovd %xmm0, %eax
; AVX-NEXT:    addb $-128, %al
; AVX-NEXT:    # kill: def $al killed $al killed $eax
; AVX-NEXT:    retq
;
; AVX512BW-LABEL: test_v4i8:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    movl $127, %eax
; AVX512BW-NEXT:    vpinsrb $4, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $5, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $6, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $7, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $8, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $9, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $10, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $11, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $12, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $13, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $14, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $15, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX512BW-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX512BW-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX512BW-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512BW-NEXT:    vmovd %xmm0, %eax
; AVX512BW-NEXT:    addb $-128, %al
; AVX512BW-NEXT:    # kill: def $al killed $al killed $eax
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v4i8:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    movl $127, %eax
; AVX512VL-NEXT:    vpinsrb $4, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $5, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $6, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $7, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $8, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $9, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $10, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $11, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $12, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $13, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $14, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $15, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpxord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %xmm0, %xmm0
; AVX512VL-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX512VL-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512VL-NEXT:    vmovd %xmm0, %eax
; AVX512VL-NEXT:    addb $-128, %al
; AVX512VL-NEXT:    # kill: def $al killed $al killed $eax
; AVX512VL-NEXT:    retq
  %1 = call i8 @llvm.vector.reduce.smin.v4i8(<4 x i8> %a0)
  ret i8 %1
}

define i8 @test_v8i8(<8 x i8> %a0) {
; SSE2-LABEL: test_v8i8:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %edx
; SSE2-NEXT:    cmpb %al, %cl
; SSE2-NEXT:    cmovll %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    cmpb %dl, %al
; SSE2-NEXT:    cmovgel %edx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    # kill: def $al killed $al killed $eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v8i8:
; SSE4:       # %bb.0:
; SSE4-NEXT:    movl $127, %eax
; SSE4-NEXT:    pinsrb $8, %eax, %xmm0
; SSE4-NEXT:    pinsrb $9, %eax, %xmm0
; SSE4-NEXT:    pinsrb $10, %eax, %xmm0
; SSE4-NEXT:    pinsrb $11, %eax, %xmm0
; SSE4-NEXT:    pinsrb $12, %eax, %xmm0
; SSE4-NEXT:    pinsrb $13, %eax, %xmm0
; SSE4-NEXT:    pinsrb $14, %eax, %xmm0
; SSE4-NEXT:    pinsrb $15, %eax, %xmm0
; SSE4-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; SSE4-NEXT:    movdqa %xmm0, %xmm1
; SSE4-NEXT:    psrlw $8, %xmm1
; SSE4-NEXT:    pminub %xmm0, %xmm1
; SSE4-NEXT:    phminposuw %xmm1, %xmm0
; SSE4-NEXT:    movd %xmm0, %eax
; SSE4-NEXT:    addb $-128, %al
; SSE4-NEXT:    # kill: def $al killed $al killed $eax
; SSE4-NEXT:    retq
;
; AVX-LABEL: test_v8i8:
; AVX:       # %bb.0:
; AVX-NEXT:    movl $127, %eax
; AVX-NEXT:    vpinsrb $8, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $9, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $10, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $11, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $12, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $13, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $14, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpinsrb $15, %eax, %xmm0, %xmm0
; AVX-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX-NEXT:    vphminposuw %xmm0, %xmm0
; AVX-NEXT:    vmovd %xmm0, %eax
; AVX-NEXT:    addb $-128, %al
; AVX-NEXT:    # kill: def $al killed $al killed $eax
; AVX-NEXT:    retq
;
; AVX512BW-LABEL: test_v8i8:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    movl $127, %eax
; AVX512BW-NEXT:    vpinsrb $8, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $9, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $10, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $11, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $12, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $13, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $14, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpinsrb $15, %eax, %xmm0, %xmm0
; AVX512BW-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX512BW-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX512BW-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX512BW-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512BW-NEXT:    vmovd %xmm0, %eax
; AVX512BW-NEXT:    addb $-128, %al
; AVX512BW-NEXT:    # kill: def $al killed $al killed $eax
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v8i8:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    movl $127, %eax
; AVX512VL-NEXT:    vpinsrb $8, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $9, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $10, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $11, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $12, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $13, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $14, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpinsrb $15, %eax, %xmm0, %xmm0
; AVX512VL-NEXT:    vpxord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %xmm0, %xmm0
; AVX512VL-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX512VL-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512VL-NEXT:    vmovd %xmm0, %eax
; AVX512VL-NEXT:    addb $-128, %al
; AVX512VL-NEXT:    # kill: def $al killed $al killed $eax
; AVX512VL-NEXT:    retq
  %1 = call i8 @llvm.vector.reduce.smin.v8i8(<8 x i8> %a0)
  ret i8 %1
}

define i8 @test_v16i8(<16 x i8> %a0) {
; SSE2-LABEL: test_v16i8:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; SSE2-NEXT:    cmpb %al, %cl
; SSE2-NEXT:    cmovll %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    # kill: def $al killed $al killed $eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v16i8:
; SSE4:       # %bb.0:
; SSE4-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; SSE4-NEXT:    movdqa %xmm0, %xmm1
; SSE4-NEXT:    psrlw $8, %xmm1
; SSE4-NEXT:    pminub %xmm0, %xmm1
; SSE4-NEXT:    phminposuw %xmm1, %xmm0
; SSE4-NEXT:    movd %xmm0, %eax
; SSE4-NEXT:    addb $-128, %al
; SSE4-NEXT:    # kill: def $al killed $al killed $eax
; SSE4-NEXT:    retq
;
; AVX-LABEL: test_v16i8:
; AVX:       # %bb.0:
; AVX-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX-NEXT:    vphminposuw %xmm0, %xmm0
; AVX-NEXT:    vmovd %xmm0, %eax
; AVX-NEXT:    addb $-128, %al
; AVX-NEXT:    # kill: def $al killed $al killed $eax
; AVX-NEXT:    retq
;
; AVX512BW-LABEL: test_v16i8:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX512BW-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX512BW-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX512BW-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512BW-NEXT:    vmovd %xmm0, %eax
; AVX512BW-NEXT:    addb $-128, %al
; AVX512BW-NEXT:    # kill: def $al killed $al killed $eax
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v16i8:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    vpxord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %xmm0, %xmm0
; AVX512VL-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX512VL-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512VL-NEXT:    vmovd %xmm0, %eax
; AVX512VL-NEXT:    addb $-128, %al
; AVX512VL-NEXT:    # kill: def $al killed $al killed $eax
; AVX512VL-NEXT:    retq
  %1 = call i8 @llvm.vector.reduce.smin.v16i8(<16 x i8> %a0)
  ret i8 %1
}

define i8 @test_v32i8(<32 x i8> %a0) {
; SSE2-LABEL: test_v32i8:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa %xmm1, %xmm2
; SSE2-NEXT:    pcmpgtb %xmm0, %xmm2
; SSE2-NEXT:    pand %xmm2, %xmm0
; SSE2-NEXT:    pandn %xmm1, %xmm2
; SSE2-NEXT:    por %xmm0, %xmm2
; SSE2-NEXT:    movdqa %xmm2, -{{[0-9]+}}(%rsp)
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %edx
; SSE2-NEXT:    cmpb %al, %cl
; SSE2-NEXT:    cmovll %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    cmpb %dl, %al
; SSE2-NEXT:    cmovgel %edx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    # kill: def $al killed $al killed $eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v32i8:
; SSE4:       # %bb.0:
; SSE4-NEXT:    pminsb %xmm1, %xmm0
; SSE4-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; SSE4-NEXT:    movdqa %xmm0, %xmm1
; SSE4-NEXT:    psrlw $8, %xmm1
; SSE4-NEXT:    pminub %xmm0, %xmm1
; SSE4-NEXT:    phminposuw %xmm1, %xmm0
; SSE4-NEXT:    movd %xmm0, %eax
; SSE4-NEXT:    addb $-128, %al
; SSE4-NEXT:    # kill: def $al killed $al killed $eax
; SSE4-NEXT:    retq
;
; AVX1-LABEL: test_v32i8:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm1
; AVX1-NEXT:    vpminsb %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX1-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX1-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vphminposuw %xmm0, %xmm0
; AVX1-NEXT:    vmovd %xmm0, %eax
; AVX1-NEXT:    addb $-128, %al
; AVX1-NEXT:    # kill: def $al killed $al killed $eax
; AVX1-NEXT:    vzeroupper
; AVX1-NEXT:    retq
;
; AVX2-LABEL: test_v32i8:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpminsb %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX2-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX2-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vphminposuw %xmm0, %xmm0
; AVX2-NEXT:    vmovd %xmm0, %eax
; AVX2-NEXT:    addb $-128, %al
; AVX2-NEXT:    # kill: def $al killed $al killed $eax
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512BW-LABEL: test_v32i8:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512BW-NEXT:    vpminsb %xmm1, %xmm0, %xmm0
; AVX512BW-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX512BW-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX512BW-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX512BW-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512BW-NEXT:    vmovd %xmm0, %eax
; AVX512BW-NEXT:    addb $-128, %al
; AVX512BW-NEXT:    # kill: def $al killed $al killed $eax
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v32i8:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512VL-NEXT:    vpminsb %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vpxord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %xmm0, %xmm0
; AVX512VL-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX512VL-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512VL-NEXT:    vmovd %xmm0, %eax
; AVX512VL-NEXT:    addb $-128, %al
; AVX512VL-NEXT:    # kill: def $al killed $al killed $eax
; AVX512VL-NEXT:    vzeroupper
; AVX512VL-NEXT:    retq
  %1 = call i8 @llvm.vector.reduce.smin.v32i8(<32 x i8> %a0)
  ret i8 %1
}

define i8 @test_v64i8(<64 x i8> %a0) {
; SSE2-LABEL: test_v64i8:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa %xmm2, %xmm4
; SSE2-NEXT:    pcmpgtb %xmm0, %xmm4
; SSE2-NEXT:    pand %xmm4, %xmm0
; SSE2-NEXT:    pandn %xmm2, %xmm4
; SSE2-NEXT:    por %xmm0, %xmm4
; SSE2-NEXT:    movdqa %xmm3, %xmm0
; SSE2-NEXT:    pcmpgtb %xmm1, %xmm0
; SSE2-NEXT:    pand %xmm0, %xmm1
; SSE2-NEXT:    pandn %xmm3, %xmm0
; SSE2-NEXT:    por %xmm1, %xmm0
; SSE2-NEXT:    movdqa %xmm0, %xmm1
; SSE2-NEXT:    pcmpgtb %xmm4, %xmm1
; SSE2-NEXT:    pand %xmm1, %xmm4
; SSE2-NEXT:    pandn %xmm0, %xmm1
; SSE2-NEXT:    por %xmm4, %xmm1
; SSE2-NEXT:    movdqa %xmm1, -{{[0-9]+}}(%rsp)
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %edx
; SSE2-NEXT:    cmpb %al, %cl
; SSE2-NEXT:    cmovll %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    cmpb %dl, %al
; SSE2-NEXT:    cmovgel %edx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    # kill: def $al killed $al killed $eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v64i8:
; SSE4:       # %bb.0:
; SSE4-NEXT:    pminsb %xmm3, %xmm1
; SSE4-NEXT:    pminsb %xmm2, %xmm0
; SSE4-NEXT:    pminsb %xmm1, %xmm0
; SSE4-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; SSE4-NEXT:    movdqa %xmm0, %xmm1
; SSE4-NEXT:    psrlw $8, %xmm1
; SSE4-NEXT:    pminub %xmm0, %xmm1
; SSE4-NEXT:    phminposuw %xmm1, %xmm0
; SSE4-NEXT:    movd %xmm0, %eax
; SSE4-NEXT:    addb $-128, %al
; SSE4-NEXT:    # kill: def $al killed $al killed $eax
; SSE4-NEXT:    retq
;
; AVX1-LABEL: test_v64i8:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm3
; AVX1-NEXT:    vpminsb %xmm2, %xmm3, %xmm2
; AVX1-NEXT:    vpminsb %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vpminsb %xmm2, %xmm0, %xmm0
; AVX1-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX1-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX1-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vphminposuw %xmm0, %xmm0
; AVX1-NEXT:    vmovd %xmm0, %eax
; AVX1-NEXT:    addb $-128, %al
; AVX1-NEXT:    # kill: def $al killed $al killed $eax
; AVX1-NEXT:    vzeroupper
; AVX1-NEXT:    retq
;
; AVX2-LABEL: test_v64i8:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpminsb %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpminsb %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX2-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX2-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vphminposuw %xmm0, %xmm0
; AVX2-NEXT:    vmovd %xmm0, %eax
; AVX2-NEXT:    addb $-128, %al
; AVX2-NEXT:    # kill: def $al killed $al killed $eax
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512BW-LABEL: test_v64i8:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vextracti64x4 $1, %zmm0, %ymm1
; AVX512BW-NEXT:    vpminsb %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512BW-NEXT:    vpminsb %xmm1, %xmm0, %xmm0
; AVX512BW-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX512BW-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX512BW-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX512BW-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512BW-NEXT:    vmovd %xmm0, %eax
; AVX512BW-NEXT:    addb $-128, %al
; AVX512BW-NEXT:    # kill: def $al killed $al killed $eax
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v64i8:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    vextracti64x4 $1, %zmm0, %ymm1
; AVX512VL-NEXT:    vpminsb %ymm1, %ymm0, %ymm0
; AVX512VL-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512VL-NEXT:    vpminsb %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vpxord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %xmm0, %xmm0
; AVX512VL-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX512VL-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512VL-NEXT:    vmovd %xmm0, %eax
; AVX512VL-NEXT:    addb $-128, %al
; AVX512VL-NEXT:    # kill: def $al killed $al killed $eax
; AVX512VL-NEXT:    vzeroupper
; AVX512VL-NEXT:    retq
  %1 = call i8 @llvm.vector.reduce.smin.v64i8(<64 x i8> %a0)
  ret i8 %1
}

define i8 @test_v128i8(<128 x i8> %a0) {
; SSE2-LABEL: test_v128i8:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa %xmm4, %xmm8
; SSE2-NEXT:    pcmpgtb %xmm0, %xmm8
; SSE2-NEXT:    pand %xmm8, %xmm0
; SSE2-NEXT:    pandn %xmm4, %xmm8
; SSE2-NEXT:    por %xmm0, %xmm8
; SSE2-NEXT:    movdqa %xmm6, %xmm4
; SSE2-NEXT:    pcmpgtb %xmm2, %xmm4
; SSE2-NEXT:    pand %xmm4, %xmm2
; SSE2-NEXT:    pandn %xmm6, %xmm4
; SSE2-NEXT:    por %xmm2, %xmm4
; SSE2-NEXT:    movdqa %xmm4, %xmm0
; SSE2-NEXT:    pcmpgtb %xmm8, %xmm0
; SSE2-NEXT:    pand %xmm0, %xmm8
; SSE2-NEXT:    pandn %xmm4, %xmm0
; SSE2-NEXT:    por %xmm8, %xmm0
; SSE2-NEXT:    movdqa %xmm5, %xmm2
; SSE2-NEXT:    pcmpgtb %xmm1, %xmm2
; SSE2-NEXT:    pand %xmm2, %xmm1
; SSE2-NEXT:    pandn %xmm5, %xmm2
; SSE2-NEXT:    por %xmm1, %xmm2
; SSE2-NEXT:    movdqa %xmm7, %xmm1
; SSE2-NEXT:    pcmpgtb %xmm3, %xmm1
; SSE2-NEXT:    pand %xmm1, %xmm3
; SSE2-NEXT:    pandn %xmm7, %xmm1
; SSE2-NEXT:    por %xmm3, %xmm1
; SSE2-NEXT:    movdqa %xmm1, %xmm3
; SSE2-NEXT:    pcmpgtb %xmm2, %xmm3
; SSE2-NEXT:    pand %xmm3, %xmm2
; SSE2-NEXT:    pandn %xmm1, %xmm3
; SSE2-NEXT:    por %xmm2, %xmm3
; SSE2-NEXT:    movdqa %xmm3, %xmm1
; SSE2-NEXT:    pcmpgtb %xmm0, %xmm1
; SSE2-NEXT:    pand %xmm1, %xmm0
; SSE2-NEXT:    pandn %xmm3, %xmm1
; SSE2-NEXT:    por %xmm0, %xmm1
; SSE2-NEXT:    movdqa %xmm1, -{{[0-9]+}}(%rsp)
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %edx
; SSE2-NEXT:    cmpb %al, %cl
; SSE2-NEXT:    cmovll %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    cmpb %dl, %al
; SSE2-NEXT:    cmovgel %edx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; SSE2-NEXT:    cmpb %cl, %al
; SSE2-NEXT:    cmovgel %ecx, %eax
; SSE2-NEXT:    # kill: def $al killed $al killed $eax
; SSE2-NEXT:    retq
;
; SSE4-LABEL: test_v128i8:
; SSE4:       # %bb.0:
; SSE4-NEXT:    pminsb %xmm7, %xmm3
; SSE4-NEXT:    pminsb %xmm5, %xmm1
; SSE4-NEXT:    pminsb %xmm3, %xmm1
; SSE4-NEXT:    pminsb %xmm6, %xmm2
; SSE4-NEXT:    pminsb %xmm4, %xmm0
; SSE4-NEXT:    pminsb %xmm2, %xmm0
; SSE4-NEXT:    pminsb %xmm1, %xmm0
; SSE4-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; SSE4-NEXT:    movdqa %xmm0, %xmm1
; SSE4-NEXT:    psrlw $8, %xmm1
; SSE4-NEXT:    pminub %xmm0, %xmm1
; SSE4-NEXT:    phminposuw %xmm1, %xmm0
; SSE4-NEXT:    movd %xmm0, %eax
; SSE4-NEXT:    addb $-128, %al
; SSE4-NEXT:    # kill: def $al killed $al killed $eax
; SSE4-NEXT:    retq
;
; AVX1-LABEL: test_v128i8:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm3, %xmm4
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm5
; AVX1-NEXT:    vpminsb %xmm4, %xmm5, %xmm4
; AVX1-NEXT:    vextractf128 $1, %ymm2, %xmm5
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm6
; AVX1-NEXT:    vpminsb %xmm5, %xmm6, %xmm5
; AVX1-NEXT:    vpminsb %xmm4, %xmm5, %xmm4
; AVX1-NEXT:    vpminsb %xmm3, %xmm1, %xmm1
; AVX1-NEXT:    vpminsb %xmm2, %xmm0, %xmm0
; AVX1-NEXT:    vpminsb %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vpminsb %xmm4, %xmm0, %xmm0
; AVX1-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX1-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX1-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vphminposuw %xmm0, %xmm0
; AVX1-NEXT:    vmovd %xmm0, %eax
; AVX1-NEXT:    addb $-128, %al
; AVX1-NEXT:    # kill: def $al killed $al killed $eax
; AVX1-NEXT:    vzeroupper
; AVX1-NEXT:    retq
;
; AVX2-LABEL: test_v128i8:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpminsb %ymm3, %ymm1, %ymm1
; AVX2-NEXT:    vpminsb %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpminsb %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX2-NEXT:    vpminsb %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX2-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX2-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vphminposuw %xmm0, %xmm0
; AVX2-NEXT:    vmovd %xmm0, %eax
; AVX2-NEXT:    addb $-128, %al
; AVX2-NEXT:    # kill: def $al killed $al killed $eax
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512BW-LABEL: test_v128i8:
; AVX512BW:       # %bb.0:
; AVX512BW-NEXT:    vpminsb %zmm1, %zmm0, %zmm0
; AVX512BW-NEXT:    vextracti64x4 $1, %zmm0, %ymm1
; AVX512BW-NEXT:    vpminsb %ymm1, %ymm0, %ymm0
; AVX512BW-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512BW-NEXT:    vpminsb %xmm1, %xmm0, %xmm0
; AVX512BW-NEXT:    vpxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX512BW-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX512BW-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX512BW-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512BW-NEXT:    vmovd %xmm0, %eax
; AVX512BW-NEXT:    addb $-128, %al
; AVX512BW-NEXT:    # kill: def $al killed $al killed $eax
; AVX512BW-NEXT:    vzeroupper
; AVX512BW-NEXT:    retq
;
; AVX512VL-LABEL: test_v128i8:
; AVX512VL:       # %bb.0:
; AVX512VL-NEXT:    vpminsb %zmm1, %zmm0, %zmm0
; AVX512VL-NEXT:    vextracti64x4 $1, %zmm0, %ymm1
; AVX512VL-NEXT:    vpminsb %ymm1, %ymm0, %ymm0
; AVX512VL-NEXT:    vextracti128 $1, %ymm0, %xmm1
; AVX512VL-NEXT:    vpminsb %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vpxord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %xmm0, %xmm0
; AVX512VL-NEXT:    vpsrlw $8, %xmm0, %xmm1
; AVX512VL-NEXT:    vpminub %xmm1, %xmm0, %xmm0
; AVX512VL-NEXT:    vphminposuw %xmm0, %xmm0
; AVX512VL-NEXT:    vmovd %xmm0, %eax
; AVX512VL-NEXT:    addb $-128, %al
; AVX512VL-NEXT:    # kill: def $al killed $al killed $eax
; AVX512VL-NEXT:    vzeroupper
; AVX512VL-NEXT:    retq
  %1 = call i8 @llvm.vector.reduce.smin.v128i8(<128 x i8> %a0)
  ret i8 %1
}

declare i64 @llvm.vector.reduce.smin.v2i64(<2 x i64>)
declare i64 @llvm.vector.reduce.smin.v4i64(<4 x i64>)
declare i64 @llvm.vector.reduce.smin.v8i64(<8 x i64>)
declare i64 @llvm.vector.reduce.smin.v16i64(<16 x i64>)

declare i32 @llvm.vector.reduce.smin.v2i32(<2 x i32>)
declare i32 @llvm.vector.reduce.smin.v4i32(<4 x i32>)
declare i32 @llvm.vector.reduce.smin.v8i32(<8 x i32>)
declare i32 @llvm.vector.reduce.smin.v16i32(<16 x i32>)
declare i32 @llvm.vector.reduce.smin.v32i32(<32 x i32>)

declare i16 @llvm.vector.reduce.smin.v2i16(<2 x i16>)
declare i16 @llvm.vector.reduce.smin.v4i16(<4 x i16>)
declare i16 @llvm.vector.reduce.smin.v8i16(<8 x i16>)
declare i16 @llvm.vector.reduce.smin.v16i16(<16 x i16>)
declare i16 @llvm.vector.reduce.smin.v32i16(<32 x i16>)
declare i16 @llvm.vector.reduce.smin.v64i16(<64 x i16>)

declare i8 @llvm.vector.reduce.smin.v2i8(<2 x i8>)
declare i8 @llvm.vector.reduce.smin.v4i8(<4 x i8>)
declare i8 @llvm.vector.reduce.smin.v8i8(<8 x i8>)
declare i8 @llvm.vector.reduce.smin.v16i8(<16 x i8>)
declare i8 @llvm.vector.reduce.smin.v32i8(<32 x i8>)
declare i8 @llvm.vector.reduce.smin.v64i8(<64 x i8>)
declare i8 @llvm.vector.reduce.smin.v128i8(<128 x i8>)
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; SSE: {{.*}}
